### ISSUE TITLE
myclient.getWorkitem( ) error

### ISSUE THREAD

**Issue by kevinhe2017** [dixudx/rtcclient#103]
Hello Everyone,

I'm trying to use Python rtcclient 0.6.0 and following the example code to get work items from RTC 6.0.3. The url ends with ccm and the RTC server doesn't have proxies. The url is like
https://rtc-ccm-1.int.xxxx.com:9443/ccm/web/projects/xxxx (note: some characters are substituted with xxxx for confidential reason).
 Here are part of sample code I use:

from rtcclient.utils import setup_basic_logging
 from rtcclient import RTCClient

setup_basic_logging()
 url = "https://rtc-ccm-1.int.xxxx.com:9443/ccm/web/projects/xxxx"
 username = "myusername"
 password = "mypassword"

myclient = RTCClient(url, username, password, ends_with_jazz=False)
 print myclient
 wk = myclient.getWorkitem("1631898")

Here are execution results (note: some characters are substituted with xxxx for confidential reason):
[results.txt](https://github.com/dixudx/rtcclient/files/1543881/results.txt)

The script seems to connect the server without issue (no error in debug log). The print command prints out "RTC Server at https://rtc-ccm-1.int.xxxx.com:9443/ccm/web/projects/xxxx" and the work item "1631898" does exist. Don't know why it still throws out "Not found <Workitem 1631898>" error.

If you have any idea, I would be grateful for your help!

**Comment by kevinhe2017** [comment]
I found that part of the cause is my url doesn't have "/oslc/workitems/". Don't know what it should be for my RTC server and project.

**Comment by dixudx** [comment]
@kevinhe2017 The url should be `https://rtc-ccm-1.int.xxxx.com:9443/ccm`. Please have a try.

**Comment by kevinhe2017** [comment]
After further investigation, I found something interesting. I went to the work item "1631898" page directly using web browser then view and save the source of this page. After that, I used Python xml parser to parse the saved HTM file and I got the same "invalid token" error.
The error from rtcclient example code:
ERROR client.RTCClient: not well-formed (invalid token): line 17, column 77

The error from python xml parser code:
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 17, column 77

The line 17 is:
<link type="text/css" rel="stylesheet" href="/ccm/web/_style/?include=L~&etag=BKxP74fi7YO_en_US&_proxyURL=%2Fccm&ss=L9ESh">

The column 77 is "g" of part "L~&etag". Don't know why it says it's not well-formed.

If I understand correctly, each function (such as getWorkitem) will get to a RTC web page then parse the page which is in xml format. If the page's source is not well-formed, it will throw errors. Don't know how to solve this kind of issues right now.

**Comment by dixudx** [comment]
@kevinhe2017 Seems the workitem (I mean xml config page) contains non-ASCII characters.

You can create a new workitem to help confirm this. Thanks.

**Comment by kevinhe2017** [comment]
Somehow line 17 is missed in last note. It is this line:
<link type="text/css" rel="stylesheet" href="/ccm/web/_style/?include=L~&etag=BKxP74fi7YO_en_US&_proxyURL=%2Fccm&ss=L9ESh">

**Comment by kevinhe2017** [comment]
What? I can't paste that line, Wired. Let me try it again.

<link type="text/css" rel="stylesheet" href="/ccm/web/_style/?include=L~&etag=BKxP74fi7YO_en_US&_proxyURL=%2Fccm&ss=L9ESh">

**Comment by kevinhe2017** [comment]
ok, let me attach it.
[Line_17.txt](https://github.com/dixudx/rtcclient/files/1546398/Line_17.txt)

**Comment by dixudx** [comment]
Please try

```python
# you need to pip install this package
import defusedexpat
```

and add/update below lines to `getWorkitem` in L914

```python
xml_cleaned = re.sub(u'[^\n\r\t\x20-\x7f]+',
                                     u'', resp.content)
raw_data = xmltodict.parse(xml_cleaned, expat=defusedexpat.pyexpat)
```

to see whether it works.

**Comment by kevinhe2017** [comment]
Tried to create work item and got the following error:
Traceback (most recent call last):
  File "C:/Users/vz9m4v/PycharmProjects/DFSS_Leon/Example.py", line 23, in <module>
    wk = myclient.createWorkitem(title='Test', copied_from="1631898")
TypeError: createWorkitem() takes at least 3 arguments (3 given)

**Comment by kevinhe2017** [comment]
Tried to create work item and got error:
Traceback (most recent call last):
  File "C:/Users/xxxx/PycharmProjects/xxxx/Example.py", line 23, in <module>
    wk = myclient.createWorkitem(title='Test', copied_from="1631898")
TypeError: createWorkitem() takes at least 3 arguments (3 given)

**Comment by dixudx** [comment]
> wk = myclient.createWorkitem(title='Test', copied_from="1631898")
TypeError: createWorkitem() takes at least 3 arguments (3 given)

Please follow the usage of this method.

**Comment by kevinhe2017** [comment]
After I installed defusedexpat package and added/updated those 2 lines, I got "ERROR client.RTCClient: global name 're' is not defined."

**Comment by kevinhe2017** [comment]
After adding "import re", still got the same error:
ERROR client.RTCClient: not well-formed (invalid token): line 17, column 77

**Comment by dixudx** [comment]
@kevinhe2017 Could you try to debug and find out why the response content (the xml data) is not well-formed?

**Comment by kevinhe2017** [comment]
Di Xu, I saw someone suggested to use lxml or beautiful soup. What do you think?

**Comment by dixudx** [comment]
> I saw someone suggested to use lxml or beautiful soup. What do you think?

This will introduce a big change for this library. I was thinking using `lxml` or `bs4`. But `xmltodict` is more easier to handle the xml data for processing.

I think the right way for now is to find out what causes the bug, the non-ascii characters, invalid xml and etc.

**Comment by kevinhe2017** [comment]
After using the following line to remove the "&" character, the "not well-formed (invalid token)" issue on line 17 is gone.

xml_cleaned = re.sub('[\&]', '', resp.content)

But I got a new issue, "ERROR client.RTCClient: mismatched tag: line 32, column 2". Don't know how to fix this type of issues.

**Comment by dixudx** [comment]
`&` is a special character. We should not replace it .

Would you please let me know the `resp.content`.

**Comment by kevinhe2017** [comment]
Here is the WT #1631898 page's source which is the resp.content. The htm file is saved as txt file. Thank you!

[Work_Ticket_1631898.txt](https://github.com/dixudx/rtcclient/files/1555833/Work_Ticket_1631898.txt)

**Comment by kevinhe2017** [comment]
@dixudx Any progress?

**Comment by dixudx** [comment]
Not yet. Did not get too much bandwidth on this. Sorry for that.

Will investigate it ASAP.

**Comment by dixudx** [comment]
@kevinhe2017 `resp.content` seems invalid.

A valid `resp.content` should contains data like [this](https://github.com/dixudx/rtcclient/blob/master/tests/fixtures/workitems.xml).

**Comment by kevinhe2017** [comment]
I added "print resp.content" in client.py to check the response content and found it's same as the source of work item page. I'm not sure why it's not like yours. I double checked with our RTC expert and he confirmed our RTC server is NOT behind a proxy so it's not proxy related. So, does the RTC server side have to do something (like some set-up) so rtcclient can get correct response?

By the way, looks like nobody in our big organization has ever used rtcclient and nobody knows how to use it. I'm the first one who starts to use it.

**Comment by kevinhe2017** [comment]
We are using RTC 6.0.3. If I understand correctly, the Python rtcclient needs to use OSLC-CM REST API. I'm not sure if we have it. How can I know if our RTC server has it? Thanks!

**Comment by dixudx** [comment]
> If I understand correctly, the Python rtcclient needs to use OSLC-CM REST API.

Correct.

> How can I know if our RTC server has it?

Actually I have no idea. Seems oslc-cm rest api is already enabled after installation. You may contact your admin.

IMO if `myclient.getWorkitem("1631898")` can successfully return right data, oslc-cm is ready to use.

**Comment by kevinhe2017** [comment]
I asked some questions on Jazz community and got some help. Looks like RTC 6.0.3 has implemented the OSLC CM v2.0 specifications. According to the document https://jazz.net/library/article/1001, applications can access, modify, delete and create change requests with an HTTP-based client by using GET, PUT, DELETE and POST methods. I didn't find where rtcclient 0.6.0 uses those GET, PUT, DELETE and POST methods. Are you using those methods?

**Comment by dixudx** [comment]
> I didn't find where rtcclient 0.6.0 uses those GET, PUT, DELETE and POST methods. Are you using those methods?

Yes. These methods are wrapped together with `requests`.

**Comment by kevinhe2017** [comment]
After further investigation, I think I finally found something. The error is "not well-formed (invalid token): line 17, column 77" which is around "L~&etag". Looks like it's related to ETag. I'm using Python 2.7.14 which has the httplib. According to a document on web, Python’s HTTP libraries do not support ETags, but httplib2 does. I just installed httplib2, but I don't know how to use it and merge it with exiting scripts. I guess I have to remove, add and change something. Could you help me? Thank you so much!

**Comment by dixudx** [comment]
@kevinhe2017 Great job on finding the root cause.

> which is around "L~&etag". Looks like it's related to ETag.
> I just installed httplib2, but I don't know how to use it and merge it with exiting scripts.

I have no idea how comes `L~&etag`. Is this field useful and meaningful? If not, I recommend you replace this string to another normal string in `response.content`. You just need to do it in the four functions in https://github.com/dixudx/rtcclient/blob/master/rtcclient/base.py#L55-L195.

**Comment by kevinhe2017** [comment]
The L~&etag is from the source of the work item page. I found it may change to A~&etag, B~&etag, etc. Etag is used for web browser cache purpose. It will check if the page has change since last visit. If not, it will get the local copy of the page content to save time and bandwidth. So it may be not useful for my project. I can replace it with another normal string.

For replacing the string, I tried response.content.replace("~&etag", "head"). It doesn't replace the ~&etag. Could you tell me the correct way to replace the etag string? And what normal string should I use?

Also, for the four functions in base.py, you mean get( ), post( ), put( ) and delete( ), correct?

**Comment by dixudx** [comment]
> For replacing the string, I tried response.content.replace("~&etag", "head"). It doesn't replace the ~&etag. Could you tell me the correct way to replace the etag string? And what normal string should I use?

You should use `response.content = response.content.replace("~&etag", "XYZ")`. You can replace `XYZ` to anything unique normal string you like, like `Foo`, `Bar` and etc.

> you mean get( ), post( ), put( ) and delete( ), correct?

Correct.

**Comment by kevinhe2017** [comment]
I found I can't replace the string in those four functions. It gives "AttributeError: can't set attribute". Also, I found the "not well-formed (invalid token): line 17, column 77" error is from "wk = myclient.getWorkitem(1631898)" and it's likely caused by "raw_data = xmltodict.parse(resp.content, expat=defusedexpat.pyexpat)". I should find out why xmltodict.parse( ) can't handle the L~&Etag.

**Comment by kevinhe2017** [comment]
I confirmed the issue is caused by xmltodict.parse( ) which can't parse not well-formatted html file. Is there alternative code to achieve the same function?

**Comment by dixudx** [comment]
@kevinhe2017 Great! Good job!

Sorry for the late reply~

> I confirmed the issue is caused by xmltodict.parse( ) which can't parse not well-formatted html file. Is there alternative code to achieve the same function?

xmltodict is easy to use. That's why I choose this.

> I found I can't replace the string in those four functions. It gives "AttributeError: can't set attribute". 

Another way to fix this is to append below contents to a new file `rtcclient/xmltodict.py`

```python
import xmltodict
try:
    from defusedexpat import pyexpat as expat
except ImportError:
    from xml.parsers import expat


def parse(xml_input, encoding=None, expat=expat, process_namespaces=False,
          namespace_separator=':', disable_entities=True, **kwargs):
    return xmltodict.parse(xml_input.replace("L~&etag", "XYZ"),
                           encoding=encoding,
                           expat=expat,
                           process_namespaces=process_namespaces,
                           namespace_separator=namespace_separator,
                           disable_entities=disable_entities, **kwargs)


def unparse(input_dict, output=None, encoding='utf-8', full_document=True,
            short_empty_elements=False,
            **kwargs):
    return xmltodict.unparse(input_dict,
                             output=output,
                             encoding=encoding,
                             full_document=full_document,
                             short_empty_elements=short_empty_elements,
                             **kwargs)
```

And override default `xmltodict` by replacing all `import xmltodict` to `from rtcclient import xmltodict` (our customized version) in other files, like `base.py`, `client.py` and etc.

**Comment by kevinhe2017** [comment]
I tried the new way and got the error "111 ERROR client.RTCClient: maximum recursion depth exceeded while calling a Python object".

By the way, I use the following code in my example.py and the client.py:
url = "https://rtc-ccm-1.int.xxx.com:9443/ccm/web"
workitem_url = "/".join([self.url,
                                    "oslc/workitems/%s" % workitem_id])
After I run it, I got the following debug output. It seems pass the authentication:
032 DEBUG client.RTCClient: Get response from https://rtc-ccm-1.int.xxx.com:9443/ccm/web/oslc/workitems/1643428

If I click the above link, I get to the following location:
https://rtc-ccm-1.int.xxx.com:9443/ccm/web
It doesn't have the oslc part like your example "http://test.url:9443/jazz/oslc/enumerations/...". Does it indicate something wrong?

If I use the following code, it can't even pass the authentication.
url = "https://rtc-ccm-1.int.xxx.com:9443/ccm"
workitem_url = "/".join([self.url,
                                    "oslc/workitems/%s" % workitem_id])

**Comment by kevinhe2017** [comment]
Also, I'm not confident it can solve the issue by replacing the L~&etag with another string and I used the xmltodict.parse( ) to parse the source code and found there may be another "mismatch tag" issue. I found this by saving the source to a HTML file and parse it using xmltodict.parse( ).

And, "https://rtc-ccm-1.int.xxx.com:9443/ccm/web#action=com.ibm.team.workitem.viewWorkItem&id=1643428" is the work item's home page address. Is the address I need to go to by using the following code?
url = "https://rtc-ccm-1.int.xxx.com:9443/ccm/web"
workitem_url = "".join([self.url,
                                     "#action=com.ibm.team.workitem.viewWorkItem&id=%s" % workitem_id])

**Comment by dixudx** [comment]
>  "https://rtc-ccm-1.int.xxx.com:9443/ccm/web#action=com.ibm.team.workitem.viewWorkItem&id=1643428" is the work item's home page address.

The url is for web. What rtcclient uses is `https://rtc-ccm-1.int.xxx.com:9443/ccm/oslc/workitems/1643428`.

@kevinhe2017 Please set `ends_with_jazz=False` when you initializes the client obj.

```
# ends_with_jazz: (optional but important) Set to `True` (default) if
# the url ends with 'jazz', otherwise to `False` if with 'ccm'
# (Refer to issue #68 for details)
myclient = RTCClient(url, username, password, ends_with_jazz=False)
```

**Comment by kevinhe2017** [comment]
First, thank you so much for your help and patience!

I do set ends_with_jazz=False when I initialize the client obj. Here is my code:
myclient = RTCClient(url, username, password, ends_with_jazz=False)

Through my recent finding, I thought the same thing: I should use https://rtc-ccm-1.int.xxx.com:9443/ccm/oslc/workitems/1643428 through the following code:
url = "https://rtc-ccm-1.int.xxx.com:9443/ccm"
workitem_url = "/".join([self.url, "oslc/workitems/%s" % workitem_id])
But, it gives errors so I think it didn't initialize the client object correctly. If I use the following code, it at least doesn't give any error. Not sure what's going on.
url = "https://rtc-ccm-1.int.xxx.com:9443/ccm/web"
workitem_url = "/".join([self.url, "oslc/workitems/%s" % workitem_id])

Here is the debug info I got
186 DEBUG client.RTCClient: Get response from https://rtc-ccm-1.int.xxx.com:9443/ccm/web/oslc/workitems/1643428
I click the above link, it goes to the following address. It doesn't go to the above address.
https://rtc-ccm-1.int.xxx.com:9443/ccm/web

**Comment by dixudx** [comment]
@kevinhe2017 The url is wrong. Should be `url = "https://rtc-ccm-1.int.xxx.com:9443/ccm"`

**Comment by kevinhe2017** [comment]
Here is the error:

2018-01-25 08:57:56,828 ERROR client.RTCClient: Failed POST request at <https://rtc-ccm-1.int.xxx.com:9443/ccm/authenticated/j_security_check> with response: Error 404: Not Found

2018-01-25 08:57:56,828 INFO client.RTCClient: 404
Traceback (most recent call last):
  File "C:/Users/xxxx/PycharmProjects/DFSS_Leon/Example.py", line 22, in <module>
    myclient = RTCClient(url, username, password, ends_with_jazz=False)
  File "C:\Python27\lib\site-packages\rtcclient\client.py", line 66, in __init__
    self.headers = self._get_headers()
  File "C:\Python27\lib\site-packages\rtcclient\client.py", line 105, in _get_headers
    allow_redirects=_allow_redirects)
  File "C:\Python27\lib\site-packages\rtcclient\utils.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\rtcclient\base.py", line 125, in post
    response.raise_for_status()
  File "C:\Python27\lib\site-packages\requests\models.py", line 936, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://rtc-ccm-1.int.xxx.com:9443/ccm/authenticated/

**Comment by kevinhe2017** [comment]
I found the resource page may be in HTML format. The rtcclient expects it in xml format. Not sure if it's part of the issues when trying to get a work item. I found many pages have the following as the first line.
<!DOCTYPE html>

**Comment by kevinhe2017** [comment]
I found the following two interesting posts. I don't fully understand the content. Maybe you know what they are talking about and if it applies to my issue.
https://jazz.net/forum/questions/244352/rtc-oslc-apis-not-working
https://www.newmediacampaigns.com/blog/browser-rest-http-accept-headers

**Comment by dixudx** [comment]
>  https://rtc-ccm-1.int.xxx.com:9443/ccm/authenticated/ 
@kevinhe2017 How come this url? This library will send requests to ` https://rtc-ccm-1.int.xxx.com:9443/ccm/authenticated/<abcd>`, not ` https://rtc-ccm-1.int.xxx.com:9443/ccm/authenticated/`. Did you change this part?

This library does add `"text/xml"` to HEADERS. And the response from rtc server is expected to be in xml format.

@kevinhe2017 Could help debug the web login requests through your browser, like [Firefox Developer Tools (used to be called Firebug)](https://developer.mozilla.org/en-US/docs/Tools).

**Comment by kevinhe2017** [comment]
1. I don't know why it changed url to https://rtc-ccm-1.int.xxx.com:9443/ccm/authenticated/.
Actually I just changed
from:
url = "https://rtc-ccm-1.int.gm.com:9443/ccm/web"
to:
url = "https://rtc-ccm-1.int.gm.com:9443/ccm"
After I run it, it gave me the error "requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://rtc-ccm-1.int.xxx.com:9443/ccm/authenticated/".

2. My original issue "not well-formed (invalid token): line 17, column 77" looks similar to an old post: https://github.com/dixudx/rtcclient/issues/68. Not sure if it's really related.

3. Also, after reviewing the following post, https://www.ibm.com/support/knowledgecenter/en/SSCP65_3.0.0/com.ibm.help.common.jazz.calm.doc/topics/t_calm_cfg_adv_props.html
I suspect our RTC administrator hasn't set the Public URI Root to https://rtc-ccm-1.int.xxx.com:9443/ccm yet. I'm going to double check with them.

**Comment by kevinhe2017** [comment]
I just checked and confirmed that my RTC Jazz Repository Connection's URI : https://rtc-ccm-1.int.xxx.com:9443/ccm/ and Name: rtc-ccm-1.int.xxx.com. It's something else which causes the authentication error.

**Comment by kevinhe2017** [comment]
By the way, after reviewing issue #93 again, I found I have the exact same issue with arun017. He seems no longer in Gitub.

**Comment by kevinhe2017** [comment]
I'm using Mozilla Firefox Chrome poster add-on to debug it, but I'm not familiar with it though. Could you tell me how to send out POST with data (username and password)?

Someone says the Failed POST request issue may be related to cookies and/or TLS 1.2. See the following links:
https://jazz.net/forum/questions/230449/vbscript-error-on-login
https://jazz.net/forum/questions/242318/authentication-issue-to-rtc-server-v602-using-c
https://jazz.net/forum/questions/32131/oauth-access-token-with-form-based-authentication

**Comment by kevinhe2017** [comment]
I noticed it's failed at GET first with response 404. It may be some clue.
2018-01-28 20:44:22,805 DEBUG urllib3.connectionpool: https://rtc-ccm-1.int.xxx.com:9443 "GET /ccm/authenticated/ HTTP/1.1" 404 None
I think this GET is same as using Chrome poster to send GET directly to URL: https://rtc-ccm-1.int.xxx.com:9443/ccm/authenticated, correct? So I sent GET using Chrome poster to https://rtc-ccm-1.int.xxx.com:9443/ccm/authenticated directly. The response status is 200 (OK) though in poster GET.

**Comment by dixudx** [comment]
> Could you tell me how to send out POST with data (username and password)?

@kevinhe2017 Just login in the web as usual and suspect all the outcome requests. You will get a clue.

**Comment by kevinhe2017** [comment]
Ah ha, I finally figured out something.

See the following interesting post:
https://jazz.net/forum/questions/151167/can-not-login-ccm-server-with-oslc-api
I followed the example and sent the following two POST commands through Chrome poster:

https://rtc-ccm-1.int.xxx.com:9443/ccm/oslc/workitems/catalog/j_security_check?j_password=mypassword&j_username=myusername

OR:
https://rtc-ccm-1.int.xxx.com:9443/ccm/oslc/workitems/catalog/j_security_check?j_username=myusername&j_password=mypassword

The responses status are all 200 (OK). Here are the first part of response:
<?xml version="1.0" encoding="UTF-8"?><oslc_disc:ServiceProviderCatalog xmlns:oslc_disc="http://open-services.net/xmlns/discovery/1.0/" rdf:about="https://rtc-ccm-1.int.xxx.com:9443/ccm/oslc/workitems/catalog.xml" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" xmlns:jfs_proc="http://jazz.net/xmlns/prod/jazz/process/1.0/" xmlns:dc="http://purl.org/dc/terms/">
<dc:title>Project Areas</dc:title>

So my question is: Can I modify your getworkitem( ) code to send POST command like the above working ones? I mean avoiding initializing a RTC client, but send some POST command to get work items directly.

By the way, if I send POST command https://rtc-ccm-1.int.xxx.com:9443/ccm/oslc/workitems/catalog/j_security_check?j_password=mypassword&j_username=myusername
with wrong username or wrong password, the response is like the following which is  "not well-formed (invalid token): line 17, column 77". It means a good POST with correct username and password is acceptable. So direct access to work items may be possible without initializing a RTC client? What do you think?
<!DOCTYPE html>


<html >
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=10">
<title></title>

<link type="text/css" rel="stylesheet" href="/ccm/web/_style/?include=0~&etag=BjJkA7H2JCU_en_US&_proxyURL=%2Fccm&

**Comment by dixudx** [comment]
@kevinhe2017 You can give it a good try in your use case.

But for common library, we still don't know what blocks the original authentication way.

**Comment by kevinhe2017** [comment]
[Response_With_Wrong_Password_Or_Username.txt](https://github.com/dixudx/rtcclient/files/1672019/Response_With_Wrong_Password_Or_Username.txt)
[Response_With_Good_Password_And_Username.txt](https://github.com/dixudx/rtcclient/files/1672020/Response_With_Good_Password_And_Username.txt)

**Comment by kevinhe2017** [comment]
Could you tell me where is the following get( ) function in getWorkitem( ) is defined? It seems to get re-directed unnecessarily when it's called.
            resp = self.get(req_url,
                            verify=False,
                            proxies=self.proxies,
                            headers=self.headers)

**Comment by kevinhe2017** [comment]
Here is the redirected GET:
2018-01-30 13:33:42,421 DEBUG client.RTCClient: Get response from https://rtc-ccm-1.int.xxx.com:9443/ccm/oslc/workitems/1643428
2018-01-30 13:33:42,421 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): rtc-ccm-1.int.xxx.com
2018-01-30 13:33:42,484 DEBUG urllib3.connectionpool: https://rtc-ccm-1.int.xxx.com:9443 "GET /ccm/oslc/workitems/1643428 HTTP/1.1" 302 0
2018-01-30 13:33:42,500 DEBUG urllib3.connectionpool: https://rtc-ccm-1.int.xxx.com:9443 "GET /ccm/secure/authenticated/identity?redirectPath=%2Fccm%2Foslc%2Fworkitems%2F1643428 HTTP/1.1" 302 0
2018-01-30 13:33:42,516 DEBUG urllib3.connectionpool: https://rtc-ccm-1.int.xxx.com:9443 "GET /ccm/auth/authrequired HTTP/1.1" 200 None

**Comment by kevinhe2017** [comment]
Never mind, I found where is get( ) defined.

**Comment by kevinhe2017** [comment]
I finally understood where my original issue "not well-formed (invalid token): line 17, column 77" comes from. It's caused by failed authentication. Although the response status is 200 OK, the response content is a html file, not a xml file. Using xmltodict.parse( ) to parse a html file, it will definitely be failed.

**Comment by kevinhe2017** [comment]
Our RTC administrator told me our RTC authentication doesn't use Kerberos protocol and the eclipse client does not use SSO. It is using a built in SSO from the middleware so the authentication through the python scripts should not have SSO. He said it should work fine without it. I don't quite understand what he said. I think the rtcclient's authentication scripts need to be tweaked for our RTC server authentication protocol. Could you provide some directions? Thank you so much in advance!

**Comment by kevinhe2017** [comment]
By the way, our RTC server uses form-based authentication.

**Comment by kevinhe2017** [comment]
Our RTC 6.0.4 is installed on a IBM WebSphere® Application Server which uses form-based authentication. I think the rtcclient 0.6.0 scripts use form-based authentication method. Don't know why it doesn't work on our RTC server.

**Comment by kevinhe2017** [comment]
Our RTC authentication url is https://rtc-ccm-1.int.xxx.com:9443/ccm/web, not https://rtc-ccm-1.int.xxx.com:9443/ccm/authenticated.

**Comment by kevinhe2017** [comment]
Here is the debug output. Could you explain why it has "GET /ccm/auth/authrequired"? I couldn't find where it's sent.

2018-01-31 16:03:17,420 DEBUG client.RTCClient: Get response from https://rtc-ccm-1.int.xxx.com:9443/ccm/authenticated/identity
2018-01-31 16:03:17,424 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): rtc-ccm-1.int.xxx.com
2018-01-31 16:03:17,766 DEBUG urllib3.connectionpool: https://rtc-ccm-1.int.xxx.com:9443 "GET /ccm/authenticated/identity HTTP/1.1" 302 0
2018-01-31 16:03:17,776 DEBUG urllib3.connectionpool: https://rtc-ccm-1.int.xxx.com:9443 "GET /ccm/auth/authrequired HTTP/1.1" 200 None
2018-01-31 16:03:17,779 DEBUG client.RTCClient: Post a request to https://rtc-ccm-1.int.xxx.com:9443/ccm/web/j_security_check with data: j_username=myusername&j_password=mypassword and json: None
2018-01-31 16:03:17,779 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): rtc-ccm-1.int.xxx.com
2018-01-31 16:03:17,828 DEBUG urllib3.connectionpool: https://rtc-ccm-1.int.xxx.com:9443 "POST /ccm/web/j_security_check HTTP/1.1" 302 0
2018-01-31 16:03:17,845 DEBUG urllib3.connectionpool: https://rtc-ccm-1.int.xxx.com:9443 "GET /ccm/web/ HTTP/1.1" 200 None
2018-01-31 16:03:17,846 DEBUG client.RTCClient: Get response from https://rtc-ccm-1.int.xxx.com:9443/ccm/authenticated/identity
2018-01-31 16:03:17,848 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): rtc-ccm-1.int.xxx.com
2018-01-31 16:03:17,892 DEBUG urllib3.connectionpool: https://rtc-ccm-1.int.xxx.com:9443 "GET /ccm/authenticated/identity HTTP/1.1" 302 0
2018-01-31 16:03:17,911 DEBUG urllib3.connectionpool: https://rtc-ccm-1.int.xxx.com:9443 "GET /ccm/auth/authrequired HTTP/1.1" 200 None

**Comment by kevinhe2017** [comment]
I was able to tweak the code so the responses are all in xml format, but the following code causes error for unknown reason:
workitem_raw = raw_data["oslc_cm:ChangeRequest"]
The raw_data is like:
OrderedDict([(u'rdf:RDF', OrderedDict([(u'@xmlns:process', u'http://jazz.net/ns/process#'), (u'@xmlns:acp', u'http://jazz.net/ns/acp#'),....

2018-01-31 20:38:59,063 ERROR client.RTCClient: 'oslc_cm:ChangeRequest'
Traceback (most recent call last):
  File "C:/Users/xxxx/PycharmProjects/DFSS_Leon/Example.py", line 25, in <module>
    wk = myclient.getWorkitem(1643428)
  File "C:\Python27\lib\site-packages\rtcclient\client.py", line 936, in getWorkitem
    raise exception.NotFound("Not found <Workitem %s>" % workitem_id)
rtcclient.exception.NotFound: Not found <Workitem 1643428>

**Comment by kevinhe2017** [comment]
After reviewing the xml response content carefully, I changed
From:
workitem_raw = raw_data["oslc_cm:ChangeRequest"]
To:
workitem_raw = raw_data["rdf:RDF"]["oslc_cm:ChangeRequest"]

It fixed the 'oslc_cm:ChangeRequest' error and goes further, but it still has other issues. Looks like I have to debug every step of the scripts.

**Comment by dixudx** [comment]
@kevinhe2017 Good job.

Seems the schema has changed.

**Comment by kevinhe2017** [comment]
@dixudx Thanks. The rtcclient seems to work fine now. I can get a specific work item at least. Actually I would like to find all the work items which are owned by someone and the type is "Implementation Work Ticket". Basically I would like to retrieve those work items' title, ID and Parent ID.

Right now I have to create a query in RTC then export the query to an excel file and process it. How can I get those information from RTC using rtcclient? Should I use the rtcclient to create a query then export the query?

**Comment by dixudx** [comment]
@kevinhe2017 Please refer [this query example](http://rtcclient.readthedocs.io/en/latest/quickstart.html#query-workitems).

**Comment by kevinhe2017** [comment]
I found the project area ID _Tf1GwI4UEeGDLvoSNiZKIA in https://rtc-ccm-1.int.xxx.com:9443/ccm/oslc/workitems/catalog

Here is part of related catalog content.
-<oslc_disc:entry>
-<oslc_disc:ServiceProvider>
<dc:title>Project Name</dc:title>
<oslc_disc:details rdf:resource="https://rtc-ccm-1.int.xxx.com:9443/ccm/process/project-areas/_Tf1GwI4UEeGDLvoSNiZKIA"/>
<oslc_disc:services rdf:resource="https://rtc-ccm-1.int.xxx.com:9443/ccm/oslc/contexts/_Tf1GwI4UEeGDLvoSNiZKIA/workitems/services.xml"/>
<jfs_proc:consumerRegistry rdf:resource="https://rtc-ccm-1.int.xxx.com:9443/ccm/process/project-areas/_Tf1GwI4UEeGDLvoSNiZKIA/links"/>
</oslc_disc:ServiceProvider>
</oslc_disc:entry>

I followed the directions in https://jazz.net/wiki/bin/view/Main/WorkItemAPIsForOSLCCM20#Examples to create the following url which I try to get all the work items which are owned by John Smith.
https://rtc-ccm-1.int.xxx.com:9443/ccm/oslc/contexts/_Tf1GwI4UEeGDLvoSNiZKIA/workitems?oslc.where=dcterms:contributor%7Bfoaf:name=%22John%20Smith%22%7D&oslc.select=dcterms:contributor%7B%2A%7D&oslc.prefix=dcterms=%3Chttp%3A//purl.org/dc/terms/%3E,foaf=%3Chttp%3A//xmlns.com/foaf/0.1/%3E

After entering the url to IE url field and hit enter, I got re-redirected to the following address.
https://rtc-ccm-1.int.xxx.com:9443/ccm/oslc/contexts/_Tf1GwI4UEeGDLvoSNiZKIA/workitems?oslc_cm.pageSize=50&_resultToken=_AFVNkAqXEeixhNS1F-YmfA&_startIndex=0

I don't understand why it got re-redirected there. Could you explain it? Maybe it's the way it is. Maybe I misunderstood the directions and I should do it differently.

**Comment by dixudx** [comment]
@kevinhe2017 Have you followed the link I gave above?

If you want to query workitem owned by someone, you can do like this

```python
>>> projectarea_name = "my_projectarea_name"
# customize your query string
>>> myquerystr = 'rtc_cm:ownedBy="John Smith"'
>>> returned_prop = "dc:title,dc:identifier,rtc_cm:state,rtc_cm:ownedBy"
>>> queried_wis = myquery.queryWorkitems(myquerystr,
                                         projectarea_name=projectarea_name,
                                         returned_properties=returned_prop)


```

**Comment by kevinhe2017** [comment]
I did follow the link you provided, but I found the queryWorkitems( ) method doesn't work as expected because the self.get( ) in _get_paged_resources( ) of client.py doesn't work. I saw the following comment in getMySavedQueries( ) in query.py. Don't know if it's the root cause.
        WARNING: now the RTC server cannot correctly list all the saved queries
        It seems to be a bug of RTC. Recommend using `runSavedQueryByUrl` to
        query all the workitems if the query is saved.

Also, I couldn't make it work using the above script. Maybe I need to modify the rtcclient scripts.

But, I saw a post which mentions to use Reportable REST API to do work item query. I tried it and it works just fine. Here is the url I tried. The response is a xml file which has all the work item information I'm interested: owned by John Smith, its summary(title) and parent IDs. That's all I need. I need to parse this xml file to get the data I'm interested.
https://rtc-ccm-1.int.xxx.com:9443/ccm/rpt/repository/workitem?fields=workitem/workItem[owner/name=%27John Smith%27]/(id|summary|parent/id)

**Comment by dixudx** [comment]
@kevinhe2017 Good job. Thanks for your time and work.

Would you help please submit several PRs to fix current problems. Seems current library cannot work well for newer RTC server. Minor updates are needed.

Really appreciate.

**Comment by kevinhe2017** [comment]
I can do that, but I'm not sure the proper way to submit PRs. Can you show me an example?

**Comment by dixudx** [comment]
@kevinhe2017 Please refer to [Creating a pull request](https://help.github.com/articles/creating-a-pull-request/).
