### ISSUE TITLE
Problems with getProjectArea

### ISSUE THREAD

**Issue by krzeelzb** [dixudx/rtcclient#113]
Traceback (most recent call last):
  File "path", line 41, in <module>
    myclient.getProjectArea(projectarea_name, archived=False, returned_properties=None)
  File "path", line 183, in getProjectArea
    projectarea_name=projectarea_name)
  File "path", line 212, in _getProjectAreas
    filter_rule=filter_rule)
  File "path", line 1371, in _get_paged_resources
    entries = (raw_data.get("oslc_cm:Collection")
AttributeError: 'NoneType' object has no attribute 'get'

Do you know what may be the cause of this problem, when I want to use :
   myclient = RTCClient(url, username, password,ends_with_jazz=True)
    myclient.getProjectArea(projectarea_name, archived=False, returned_properties=None)

**Comment by dixudx** [comment]
> in _get_paged_resources entries = (raw_data.get("oslc_cm:Collection")
AttributeError: 'NoneType' object has no attribute 'get'

Seems the raw_data here is none.

@krzeelzb Have you provided the right login info? It seems the client does not get the correct login token. And strangely it does not occur any error.

**Comment by krzeelzb** [comment]
Username and password, I am sure about. Could it be because of bad url?

**Comment by krzeelzb** [comment]
Username and password, I am sure about. Could it be because of bad url?

**Comment by krzeelzb** [comment]
When I use different url, then I have different error: 
`parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line X, column Y`

**Comment by dixudx** [comment]
> Could it be because of bad url?

Yeah, probably. This url is not random. It normally is something like `https://your_domain:9443/jazz`.

**Comment by krzeelzb** [comment]
Ok, I changed url and still sth not working:
  `  raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='rtc.intel.com', port=9443): Max retries exceeded with url: /jazz/authenticated/identity (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000005E8FC88>: Failed to establish a new connection: [Errno 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond',))`

**Comment by dixudx** [comment]
@krzeelzb What does your url look like?

And please enable debug logging mode.

```python
>>> from rtcclient import RTCClient
# you can remove this if you don't need logging
# default debug logging for console output
>>> setup_basic_logging()
```

**Comment by krzeelzb** [comment]
still the same problem:(
