### ISSUE TITLE
CreateWorkItem/CopyWorkItem do not work

### ISSUE THREAD

**Issue by waltercmg** [dixudx/rtcclient#114]
Hello,

When i try create or copy a workitem, as bellow:

`myclient = RTCClient(url, username, password, ends_with_jazz=False)
new = myclient.copyWorkitem(copied_from=17079,title="", description="")`

This error occurs:

`2018-10-23 09:28:06,742 INFO client.RTCClient: 404
Traceback (most recent call last):
  File "teste_criar_item_alm.py", line 87, in <module>
    main()
  File "teste_criar_item_alm.py", line 69, in main
    novo = myclient.copyWorkitem(copied_from=17079,title="", description="")
  File "/home/00937325465/.local/lib/python2.7/site-packages/rtcclient/client.py", line 1114, in copyWorkitem
    return self._createWorkitem(wi_url_post, wi_raw)
  File "/home/00937325465/.local/lib/python2.7/site-packages/rtcclient/client.py", line 1122, in _createWorkitem
    data=workitem_raw)
  File "/home/00937325465/.local/lib/python2.7/site-packages/rtcclient/utils.py", line 26, in wrapper
    resp = func(*args, **kwargs)
  File "/home/00937325465/.local/lib/python2.7/site-packages/rtcclient/base.py", line 123, in post
    response.raise_for_status()
  File "/home/00937325465/.local/lib/python2.7/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://desenvalm.serpro/ccm/oslc/contexts/_0vRmoD5sEeSB165LvJ-Jhw/workitems/Tarefa`

**Comment by dixudx** [comment]
@waltercmg You have specified an empty title, which is invalid or not supported. The `title` here is for your new workitem.

**Comment by hylsp** [comment]
I tried the copy，but it shows like this：RuntimeError: OrderedDict mutated during iteration
