### ISSUE TITLE
The element type "oslc_cm:ChangeRequest" must be terminated by the matching end-tag

### ISSUE THREAD

**Issue by gbecki** [dixudx/rtcclient#123]
Hi Di Xu

When i'm try to create Workitem or copy an existent, i get:

<oslc_cm:message>Malformed XML: The element type "oslc_cm:ChangeRequest" must be terminated by the matching end-tag "&lt;/oslc_cm:ChangeRequest&gt;".</oslc_cm:message>
</oslc_cm:error>
2019-12-26 16:06:52,521 INFO client.RTCClient: 400

Do you have any clues about the error?

RTC version: 6.0.4
Python version : 2.7.12

Ps: Nice project

Thank you.

**Comment by dixudx** [comment]
@gbecki Would you please provide a piece of your codes on how you created a Workitem. And the error stack track as well.

**Comment by gbecki** [comment]
Hey @dixudx tks for you reply.

```python
myclient.createWorkitem(item_type='Incidente', title='Teste123', description='Teste123', projectarea_name='MIB 2.0', projectarea_id='_moJeAH_FEei-sv3TdZXl1w', template='alerta.template.txt', priority='Preciso ser atendido agora', severity='Crítica', keep=False)
```
<pre>
</oslc_cm:ChangeRequest> and json: None
2019-12-27 10:43:09,468 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): clm.rtcserver.internal:443
2019-12-27 10:43:09,482 DEBUG urllib3.connectionpool: https://clm.rtcserver.internal:443 "POST /ccm/oslc/contexts/_moJeAH_FEei-sv3TdZXl1w/workitems/incidente_mib HTTP/1.1" 400 330
2019-12-27 10:43:09,483 ERROR client.RTCClient: Failed POST request at <https://clm.rtcserver.internal/ccm/oslc/contexts/_moJeAH_FEei-sv3TdZXl1w/workitems/incidente_mib> with response: <?xml version="1.0" encoding="UTF-8"?><oslc_cm:error xmlns:oslc_cm="http://open-services.net/xmlns/cm/1.0/">
<oslc_cm:status>400</oslc_cm:status>
<oslc_cm:message>Malformed XML: The element type "oslc_cm:ChangeRequest" must be terminated by the matching end-tag "&lt;/oslc_cm:ChangeRequest&gt;".</oslc_cm:message>
</oslc_cm:error>
2019-12-27 10:43:09,483 INFO client.RTCClient: 400
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/rtcclient/client.py", line 1073, in createWorkitem
    return self._createWorkitem(wi_url_post, wi_raw)
  File "/usr/local/lib/python2.7/dist-packages/rtcclient/client.py", line 1121, in _createWorkitem
    data=workitem_raw)
  File "/usr/local/lib/python2.7/dist-packages/rtcclient/utils.py", line 26, in wrapper
    resp = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rtcclient/base.py", line 123, in post
    response.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://clm.rtcserver.internal/ccm/oslc/contexts/_moJeAH_FEei-sv3TdZXl1w/workitems/incidente_mib
</pre>

Template: [alerta.template.txt](https://github.com/dixudx/rtcclient/files/4005432/alerta.template.txt)

Please let me know if you need more information.
gbecki

**Comment by dixudx** [comment]
@gbecki 

After inspecting your template, L24 is suspicious. Please remove it and have a try.
```
<rtc_cm:evidencias_mib>&lt;a href="http://monitoramento.prometheus.internal/alertmanager/#/alerts?receiver=monitoramento_sede"&gt;http://monitoramento.prometheus.internal/alertmanager/#/alerts?receiver=monitoramento_sede&lt;/a&gt;</rtc_cm:evidencias_mib>
```

**Comment by gbecki** [comment]
@dixudx
 
Yes, I am already remove this line earlier, but unfortunately the error persists.
Using another template generated from other existing task, the error is different:
```
<oslc_cm:status>400</oslc_cm:status>
<oslc_cm:message>Malformed XML: XML document structures must start and end within the same entity.</oslc_cm:message>
</oslc_cm:error>
2020-01-03 14:26:59,260 INFO client.RTCClient: 400
```

I will try to create from another Factory with simpler arguments.

Thank you
