### ISSUE TITLE
"(invalid token): line 17, column 77" error when trying to getWorkItem

### ISSUE THREAD

**Issue by MartinBarkerPhilips** [dixudx/rtcclient#146]
Hello, I am trying to use the rtcclient python package to authenticate and retrieve work items from my board. Specifically to run a command like this without error: `myclient.getWorkitem("202007")`

But when I run that command, after a bunch of debug output shwoing 200 and 302 status codes, I get an error when client.py tries to parse xml data from a response:
`2022-02-22 15:24:21,540 ERROR client.RTCClient: not well-formed (invalid token): line 17, column 77`
 
It seems like client.py is making a request to the workitem URL, if i view that url in my browser it looks like legit good xml data, but when client.py tries to make the request, it returns a small amount of html data that throws an error when it gets sent through "xmltodict".

Here are the steps I have taken to examine this issue:

- Cloned github repo, installed requirerments.txt
- Uninstall/reinstall rtcclient using my downloaded local github repo folder:
	pip uninstall rtcclient
	pip install -e rtcclient
- Start python shell 
	python
- Input these commands in the shell:
    ```
	>>> from rtcclient.utils import setup_basic_logging
	>>> from rtcclient import RTCClient
	>>> setup_basic_logging()
	>>> myclient = RTCClient("https://rtcus1.ta.philips.com/ccm", "myUsername", "myPassword", ends_with_jazz=True)
    ```
- Running the `myclient=RTCClient(…)` line results in an error:
	```
	requests.exceptions.SSLError: HTTPSConnectionPool(host='rtcus1.ta.philips.com', port=443): Max retries exceeded with url: /ccm/authenticated/identity (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:997)')))
	```
- So in rtcclient/rtcclient/base.py I add the following code before line 77 `response = requests.get(url, verify=verify, headers=headers,proxies=proxies, timeout=timeout, **kwargs)`
	```
	requests.packages.urllib3.disable_warnings()
	requests.packages.urllib3.util.ssl_.DEFAULT_CIPHERS += ':HIGH:!DH:!aNULL'
	try:
	    requests.packages.urllib3.contrib.pyopenssl.util.ssl_.DEFAULT_CIPHERS += ':HIGH:!DH:!aNULL'
	except AttributeError:
	    # no pyopenssl support used / needed / available
	    pass
	```
- I exit python shell `exit()`, start it back up `python`, and re-enter the following commands:
    ```
	>>> from rtcclient.utils import setup_basic_logging
	>>> from rtcclient import RTCClient
	>>> setup_basic_logging()
	>>> myclient = RTCClient("https://rtcus1.ta.philips.com/ccm", "myUsername", "myPassword", ends_with_jazz=True)
    ```
- now when the last line runs, I get output with 200 and 302 response status codes:
    ```
	>>> myclient = RTCClient("https://rtcus1.ta.philips.com/ccm", "myUsername", "myPassword", ends_with_jazz=True)
	2022-02-22 15:03:08,876 DEBUG client.RTCClient: Get response from https://rtcus1.ta.philips.com/ccm/authenticated/identity
	2022-02-22 15:03:08,884 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): rtcus1.ta.philips.com:443
	2022-02-22 15:03:09,555 DEBUG urllib3.connectionpool: [https://rtcus1.ta.philips.com:443](https://rtcus1.ta.philips.com/) "GET /ccm/authenticated/identity HTTP/1.1" 302 0
	2022-02-22 15:03:09,702 DEBUG urllib3.connectionpool: [https://rtcus1.ta.philips.com:443](https://rtcus1.ta.philips.com/) "GET /ccm/auth/authrequired HTTP/1.1" 200 None
	2022-02-22 15:03:09,710 DEBUG client.RTCClient: Get response from https://rtcus1.ta.philips.com/ccm/authenticated/identity
	2022-02-22 15:03:09,718 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): rtcus1.ta.philips.com:443
	2022-02-22 15:03:10,488 DEBUG urllib3.connectionpool: [https://rtcus1.ta.philips.com:443](https://rtcus1.ta.philips.com/) "GET /ccm/authenticated/identity HTTP/1.1" 302 0
	2022-02-22 15:03:10,623 DEBUG urllib3.connectionpool: [https://rtcus1.ta.philips.com:443](https://rtcus1.ta.philips.com/) "GET /ccm/auth/authrequired HTTP/1.1" 200 None
	>>>
    ```
- It finished without error, so next I try to run this python command to get a work item:
    ```
	>>> myclient.getWorkitem("202007")
    ```
- There is a lot of output with many debug lines, including 200 and 302 response codes. Eventually I get an error message:
    ```
	2022-02-22 15:11:19,389 DEBUG urllib3.connectionpool: [https://rtcus1.ta.philips.com:443](https://rtcus1.ta.philips.com/) "GET /ccm/auth/authrequired HTTP/1.1" 200 None
	2022-02-22 15:11:19,398 ERROR client.RTCClient: not well-formed (invalid token): line 17, column 77
	Traceback (most recent call last):
	  File "C:\Users\myUsername\Documents\repos\rtcclient\rtcclient\client.py", line 909, in getWorkitem
	    raw_data = xmltodict.parse(resp.content)
	  File "C:\Users\myUsername\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\xmltodict.py", line 327, in parse
	    parser.Parse(xml_input, True)
	xml.parsers.expat.ExpatError: not well-formed (invalid token): line 17, column 77
	
	During handling of the above exception, another exception occurred:
	
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "C:\Users\myUsername\Documents\repos\rtcclient\rtcclient\client.py", line 923, in getWorkitem
	    raise exception.NotFound("Not found <Workitem %s>" % workitem_id)
	rtcclient.exception.NotFound: Not found <Workitem 202007>
	>>>
    ```
- Line 909 of client.py is this:
	```
    raw_data = xmltodict.parse(resp.content)
    ```
- I added some lines surrounding client.py to examine what is beign requested, and what the contents of resp.content are:
	```
            print("\n req_url = ", req_url, "\n")

            resp = self.get(req_url,
                            verify=False,
                            proxies=self.proxies,
                            headers=self.headers)

            print("\n resp.content = ", resp.content, "\n")

            raw_data = xmltodict.parse(resp.content)

            workitem_raw = raw_data["oslc_cm:ChangeRequest"]

	```
- When I exit() and start python shell and run all my commands again, once I run `myclient.getWorkitem("202007")` I can see this output:
    ```
	>>> myclient.getWorkitem("202007")
	
	 req_url =  https://rtcus1.ta.philips.com/ccm/oslc/workitems/202007
	
	2022-02-22 15:24:19,226 DEBUG urllib3.connectionpool: [https://rtcus1.ta.philips.com:443](https://rtcus1.ta.philips.com/) "GET /ccm/auth/authrequired HTTP/1.1" 200 None
	2022-02-22 15:24:19,230 INFO client.RTCClient: Cookie expires. Relogin to get a new cookie.
	2022-02-22 15:24:19,231 DEBUG client.RTCClient: Get response from https://rtcus1.ta.philips.com/ccm/authenticated/identity
	2022-02-22 15:24:19,234 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): rtcus1.ta.philips.com:443
	…… lots of these debug lines untill eventually: ….
	
	 resp.content =  b'<!DOCTYPE html>\n<!--\n  Licensed Materials - Property of IBM\n  (c) Copyright IBM Corporation 2005, 2015. All Rights Reserved.\n  \n  Note to U.S. Government Users Restricted Rights:\n  Use, duplication or disclosure restricted by GSA ADP Schedule\n  Contract with IBM Corp.\n-->\n\n<html >\n<head>\n<meta http-equiv="content-type" content="text/html; charset=UTF-8">\n<meta http-equiv="X-UA-Compatible" content="IE=10">\n<title></title>\n\n<link type="text/css" rel="stylesheet" href="/ccm/web/_style/?include=I~&etag=DNUGfMa3f0f_en_US&_proxyURL=%2Fccm&ss=U6sUn">\n<link rel="shortcut icon" href="/ccm/web/net.jazz.ajax/jazz.ico">\n\n<style type="text/css">\n#net-jazz-ajax-NoScriptMessage {\n\twidth: 100%;\n\tcolor: #D0D0D0;\n\tfont-size: 2em;\n\ttext-align: center;\n\tposition: absolute;\n\ttop: 1%;\n\tz-index: 999;\n}\n</style>\n\n</head>\n\n<body class="claro">\n\t<noscript><div id="net-jazz-ajax-NoScriptMessage">Javascript is either disabled or not available in your Browser</div></noscript>\n\t<div id="net-jazz-ajax-InitialLoadMessage">Loading...</div>\n\t<div id="net-jazz-ajax-WorkbenchRoot"></div>\n\t\n\t<script type="text/javascript">\n\t\tdjConfig = {\n\t\t\tisDebug: false,\n\t\t\tusePlainJson: true,\n\t\t\tbaseUrl: "/ccm/web/dojo/",\n\t\t\tlocale: "en-us",\n\t\t\tlocalizationComplete: true\n\t\t};\n\t\t/*null*/\n\t\tnet = {jazz: {ajax: {}}};\n\t\tnet.jazz.ajax._contextRoot = "/ccm";\n\t\tnet.jazz.ajax._appPath = "/ccm/auth/authrequired";\n\t\tnet.jazz.ajax._webuiPrefix = "/web/";\n\t</script>\n\t\n\t<script type="text/javascript" src="/ccm/web/_js/?include=I~&etag=DNUGfMa3f0f_en_US&_proxyURL=%2Fccm&ss=U6sUn&locale=en-us"></script>\n\n<script type="text/javascript">\nrequire("dojo/main").getObject(\'jazz.core.loader\', true)._serverStartup="U6sUn";\nrequire("dojo/main").getObject(\'jazz.core.loader\',true)._loaded=["I"];\n</script>\n\n\t\n\t<script type="text/javascript">\n\t/* <![CDATA[ */\n\t\tdojo.addOnLoad( function() {\n\t\t\tnet.jazz.ajax.ui.PlatformUI.createAndRunWorkbench("net.jazz.web.app.authrequired");\n\t\t});\n\t/* ]]> */\n\t</script>\n</body>\n</html>\n'  
	```
- So my resp.content is coming in as html byte data (because it starts with b'<... )
- When it tries to get parsed with the line `xmltodict.parse(resp.content)` it leads to the error:
	ERROR client.RTCClient: not well-formed (invalid token): line 17, column 77
- If I visit the req_url (https://rtcus1.ta.philips.com/ccm/oslc/workitems/202007) in my browser it successfully goes to an xml file with  oslc_cm:ChangeRequest visible.
- But If you clean up the resp.content html and view it in a browser, it jus shows the text `Loading...`
- Is my `resp = self.get(req_url ` line not waiting for the page to load before returning?
- Or is the html byte response correct, and the `ERROR client.RTCClient: not well-formed (invalid token): line 17, column 77` error caused by something else?

**Comment by dixudx** [comment]
@MartinBarkerPhilips Seems the authentication is not okay.

Please try setting `ends_with_jazz` to False,

```python
myclient = RTCClient("https://rtcus1.ta.philips.com/ccm", "myUsername", "myPassword", ends_with_jazz=False)
```

**Comment by MartinBarkerPhilips** [comment]
@dixudx I tried going through my steps with ends_with_jazz=True but it resulted in the same html error instead of xml. I found a post online which sounds like exactly what my issue is: 
https://jazz.net/forum/questions/248769/how-to-resolve-issue-with-oslc-workshop-getting-error-javascript-is-either-disabled-or-not-available-in-your-browser

I'm trying to understand, maybe I'm not authenticating correctly?

**Comment by dixudx** [comment]
> the issue was that I was using the most recent version, using version 0.6.0 works!
