### ISSUE TITLE
resp.content doesn't have real xml format data 

### ISSUE THREAD

**Issue by MichelleBX** [dixudx/rtcclient#161]
resp.content doesn't have real xml format data 
=====
Trying rtcclient 8.0.1 for RTC 6.0.6.1, using url with /ccm path. Authentication seems ok, though pulling data,  it doesn't have real ones, instead giving some "Copyright .. ".  Testing script is as below: 

url = "https://my-rtc-server-url/ccm"
username = "uuu"
password = "ppp"
myclient = RTCClient(url, username, password, ends_with_jazz=False)
workarea = myclient.getProjectArea(projectarea_name)

======
Added several printout with line numbers in client.py for more details:
XXPP #1422: **url: https://my-rtc-server-url/ccm/oslc/projectareas?oslc_cm.pageSize=10&_startIndex=0**
XXPP #1422: resp: <Response [200]>
XXPP #1422: content: "b'<!DOCTYPE html>\n\n\n<html >\n<head>\n<meta http-equiv="content-type" content="text/html; charset=UTF-8">\n<meta http-equiv="X-UA-Compatible" content="IE=10">\n<title></title>\n\n<link type="text/css" rel="stylesheet" href="/ccm/web/_style/?include=A~&etag=ECUucKk2mAo_en_US&_proxyURL=%2Fccm&ss=Vevn9">\n<link rel="shortcut icon" href="/ccm/web/net.jazz.ajax/jazz.ico">\n\n<style type="text/css">\n#net-jazz-ajax-NoScriptMessage {\n\twidth: 100%;\n\tcolor: #D0D0D0;\n\tfont-size: 2em;\n\ttext-align: center;\n\tposition: absolute;\n\ttop: 1%;\n\tz-index: 999;\n}\n</style>\n\n</head>\n\n<body class="claro">\n\t<noscript><div id="net-jazz-ajax-NoScriptMessage">Javascript is either disabled or not available in your Browser</div></noscript>\n\t<div id="net-jazz-ajax-InitialLoadMessage">Loading...</div>\n\t<div id="net-jazz-ajax-WorkbenchRoot"></div>\n\t\n\t<script type="text/javascript">\n\t\tdjConfig = {\n\t\t\tisDebug: false,\n\t\t\tlayout: "",\n\t\t\tusePlainJson: true,\n\t\t\tbaseUrl: "/ccm/web/dojo/",\n\t\t\tlocale: "en-us",\n\t\t\tlocalizationComplete: true\n\t\t};\n\t\t/*null*/\n\t\tnet = {jazz: {ajax: {}}};\n\t\tnet.jazz.ajax._contextRoot = "/ccm";\n\t\tnet.jazz.ajax._webuiPrefix = "/web/";\n\t</script>\n\t\n\t<script type="text/javascript" src="/ccm/web/_js/?include=A~&etag=ECUucKk2mAo_en_US&_proxyURL=%2Fccm&ss=Vevn9&locale=en-us"></script>\n\n<script type="text/javascript">\nrequire("dojo/main").getObject(\'jazz.core.loader\', true)._serverStartup="Vevn9";\nrequire("dojo/main").getObject(\'jazz.core.loader\',true)._loaded=["A"];\n</script>\n\n\t\n\t<script type="text/javascript">\n\t/* <![CDATA[ */\n\t\tdojo.addOnLoad( function() {\n\t\t\tnet.jazz.ajax.ui.PlatformUI.createAndRunWorkbench("net.jazz.web.app.authrequired");\n\t\t});\n\t/* ]]> */\n\t</script>\n</body>\n</html>\n'"

XXPP #1422: headers: {'X-Powered-By': 'Servlet/3.0', 'Strict-Transport-Security': 'max-age=31536000', 'X-com-ibm-team-repository-web-auth-msg': 'authrequired', 'X-XSS-Protection': '1; mode=block', 'Content-Type': 'text/html; charset=UTF-8', 'Content-Encoding': 'gzip', 'Content-Language': 'en-US', 'Content-Length': '1016', 'Set-Cookie': 'JazzFormAuth=Form; Path=/ccm; Secure', 'Date': 'Fri, 03 Jun 2022 21:02:36 GMT', 'Expires': 'Thu, 01 Dec 1994 16:00:00 GMT', 'Cache-Control': 'no-cache="set-cookie, set-cookie2"'}

======
By directly loading **url: https://my-rtc-server-url/ccm/oslc/projectareas?oslc_cm.pageSize=10&_startIndex=0**, content in xml format shows all right. 

Is there any additional settings / configuration that it needs to retrieve the content properly? Thanks a lot!

**Comment by dixudx** [comment]
> XXPP #1422: url: https://my-rtc-server-url/ccm/oslc/projectareas?oslc_cm.pageSize=10&_startIndex=0
XXPP #1422: resp: <Response [200]>
XXPP #1422: content: "b'\n\n\n\n\n\n\n<title></title>\n\n\n\n\n<style type="text/css">\n#net-jazz-ajax-NoScriptMessage {\n\twidth: 100%;\n\tcolor: #D0D0D0;\n\tfont-size: 2em;\n\ttext-align: center;\n\tposition: absolute;\n\ttop: 1%;\n\tz-index: 999;\n}\n</style>\n\n\n\n\n\t

>By directly loading url: https://my-rtc-server-url/ccm/oslc/projectareas?oslc_cm.pageSize=10&_startIndex=0, content in xml format shows all right.

It is supposed to be an auth issue. Would you please share some log message on the authentication?

And please try using rtcclient with version 0.6.0 with `pip install -U rtcclient==0.6.0` to see whether it works.

**Comment by MichelleBX** [comment]
Thanks for the quick response. Version 0.6.0 does help passed the authentication step. I copied _get_headers() from 0.6.0 to 0.8.1, I was able to retrieve xml format data for "Project Area" attributes. 
Though at this point it complains while it tried to parse the data. 
2022-06-06 15:10:44,767 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): ffx-rtc-app.msc.fema.gov:443
2022-06-06 15:10:48,105 DEBUG urllib3.connectionpool: https://ffx-rtc-app.msc.fema.gov:443 "GET /ccm/oslc/projectareas?oslc_cm.pageSize=10&_startIndex=0 HTTP/1.1" 200 900
Traceback (most recent call last):
  File "C:\Users\MICHELLEXIE\Desktop\test.py", line 22, in <module>
    workarea = myclient.getProjectArea(projectarea_name)
  File "C:\Users\MICHELLEXIE\AppData\Roaming\Python\Python310\site-packages\rtcclient\client.py", line 236, in getProjectArea
    proj_areas = self._getProjectAreas(archived=archived,
  File "C:\Users\MICHELLEXIE\AppData\Roaming\Python\Python310\site-packages\rtcclient\client.py", line 265, in _getProjectAreas
    return self._get_paged_resources("ProjectArea",
  File "C:\Users\MICHELLEXIE\AppData\Roaming\Python\Python310\site-packages\rtcclient\client.py", line 1514, in _get_paged_resources
    p.starmap(self._handle_resource_entry,
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\MICHELLEXIE\AppData\Roaming\Python\Python310\site-packages\rtcclient\client.py", line 1578, in _handle_resource_entry
    entry_archived = entry.get("rtc_cm:archived")
AttributeError: 'str' object has no attribute 'get'

**Comment by MichelleBX** [comment]
Thanks a lot for the quick response. Version 0.6.0 does help passed the authentication step. I copied _get_header() from 0.6.0 to replace the function in 0.8.1, I was able to get xml format data. While it tried to parse the data, it failed: 
2022-06-06 15:10:44,767 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): my-rtc-server-url:443
2022-06-06 15:10:48,105 DEBUG urllib3.connectionpool: https://my-rtc-server-url "GET /ccm/oslc/projectareas?oslc_cm.pageSize=10&_startIndex=0 HTTP/1.1" 200 900
Traceback (most recent call last):
  File "C:\Users\MICHELLEXIE\Desktop\test.py", line 22, in <module>
    workarea = myclient.getProjectArea(projectarea_name)
  File "C:\Users\MICHELLEXIE\AppData\Roaming\Python\Python310\site-packages\rtcclient\client.py", line 236, in getProjectArea
    proj_areas = self._getProjectAreas(archived=archived,
  File "C:\Users\MICHELLEXIE\AppData\Roaming\Python\Python310\site-packages\rtcclient\client.py", line 265, in _getProjectAreas
    return self._get_paged_resources("ProjectArea",
  File "C:\Users\MICHELLEXIE\AppData\Roaming\Python\Python310\site-packages\rtcclient\client.py", line 1514, in _get_paged_resources
    p.starmap(self._handle_resource_entry,
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Program Files\Python310\lib\multiprocessing\pool.py", line 51, in starmapstar
    return list(itertools.starmap(args[0], args[1]))
  File "C:\Users\MICHELLEXIE\AppData\Roaming\Python\Python310\site-packages\rtcclient\client.py", line 1578, in _handle_resource_entry
    entry_archived = entry.get("rtc_cm:archived")
AttributeError: 'str' object has no attribute 'get'
[client.py.txt](https://github.com/dixudx/rtcclient/files/8847043/client.py.txt)

**Comment by dixudx** [comment]
@MichelleBX Glad to know it works.

rtcclient 0.7.0 introduced an auth change for RTC and ELM with higher version. So we may need to stick with rtcclient 0.6.0 if we are using older version RTC/ELM.

**Comment by MichelleBX** [comment]
Thanks for prompt response, and suggestions. I am able to resolve the issue and move forwards.
