### ISSUE TITLE
Incompatible with Jazz 7.0.2

### ISSUE THREAD

**Issue by Mershl** [dixudx/rtcclient#166]
Hi @dixudx,

We upgraded to Jazz 7.0.2 and with it I wanted to upgrade rtcclient to its latest and greatest version.

My findings so far:
- All get requests in `client.py` without the explicit auth tuple report an `401 - Unauhorized` error. This is fixed by adding an explicit `auth=(self.username, self.password)` to every `self.get` request coming from `client.py`.
- paged_resources (like projectareas) fail with an `expired query error` (the same error is visible when executing the generated request in a web browser).

OSLC response for `createWorkitem` -> `getProjectArea` ->  `_getProjectAreas` -> `_get_paged_resources`:
```
<oslc_cm:error>
  <oslc_cm:status>500</oslc_cm:status>
  <oslc_cm:message>Query _PBIIUANdEe2A47bFfUIiyQ expired.</oslc_cm:message>
</oslc_cm:error>
```

Do you have an idea where the later issue could come from? Feel free to pass me a guess and I'll implement and test it against 7.0.2.

**Comment by dixudx** [comment]
> All get requests in client.py without the explicit auth tuple report an 401 - Unauhorized error. This is fixed by adding an explicit auth=(self.username, self.password) to every self.get request coming from client.py

This is strange. But luckily you got a solution.

I was wondering whether the `token` was not needed anymore in Jazz 7.0.2.

> paged_resources (like projectareas) fail with an expired query error (the same error is visible when executing the generated request in a web browser)
> Query _PBIIUANdEe2A47bFfUIiyQ expired.

I think we can try to add explicit `auth=(self.username, self.password)` to `self.get` and `self.post`. Let's see what happens.

**Comment by Mershl** [comment]
> I think we can try to add explicit auth=(self.username, self.password) to self.get and self.post. Let's see what happens.

This fixes the first set of issues and leaves us only with the "Query expired" error.

OSLC response for createWorkitem -> getProjectArea -> _getProjectAreas -> _get_paged_resources:

```
<oslc_cm:error>
  <oslc_cm:status>500</oslc_cm:status>
  <oslc_cm:message>Query _PBIIUANdEe2A47bFfUIiyQ expired.</oslc_cm:message>
</oslc_cm:error>
```

**Comment by dixudx** [comment]
Please help verify this query `_PBIIUANdEe2A47bFfUIiyQ` with your browser and see what happened.

**Comment by Mershl** [comment]
Execution log for creating a workitem:
```
2022-07-19 13:53:50,133 DEBUG client.RTCClient: Get response from https://foobar.com/ccm/authenticated/identity
2022-07-19 13:53:50,137 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): foobar.com:443
2022-07-19 13:53:52,753 DEBUG urllib3.connectionpool: https://foobar.com:443 "GET /ccm/authenticated/identity HTTP/1.1" 302 0
2022-07-19 13:53:53,090 DEBUG urllib3.connectionpool: https://foobar.com:443 "GET /ccm/authenticated_identity HTTP/1.1" 200 58
2022-07-19 13:53:53,094 DEBUG client.RTCClient: Get response from https://foobar.com/ccm/authenticated/identity
2022-07-19 13:53:53,096 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): foobar.com:443
2022-07-19 13:53:55,505 DEBUG urllib3.connectionpool: https://foobar.com:443 "GET /ccm/authenticated/identity HTTP/1.1" 302 0
2022-07-19 13:53:55,636 DEBUG urllib3.connectionpool: https://foobar.com:443 "GET /ccm/authenticated_identity HTTP/1.1" 200 58
2022-07-19 13:53:55,644 DEBUG client.RTCClient: Try to get <ProjectArea ExampleProjectArea>
2022-07-19 13:53:55,645 DEBUG client.RTCClient: Start to fetch all ProjectAreas with [ProjectArea ID: not specified] and [archived=False]
2022-07-19 13:53:55,645 DEBUG client.RTCClient: Get response from https://foobar.com/ccm/oslc/projectareas?oslc_cm.pageSize=10&_startIndex=0
2022-07-19 13:53:55,648 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): foobar.com:443
2022-07-19 13:53:58,457 DEBUG urllib3.connectionpool: https://foobar.com:443 "GET /ccm/oslc/projectareas?oslc_cm.pageSize=10&_startIndex=0 HTTP/1.1" 200 7548
2022-07-19 13:53:58,469 DEBUG client.RTCClient: Get response from https://foobar.com/ccm/oslc/projectareas?oslc_cm.pageSize=10&_resultToken=_eRmhQAdZEe2uavfh6co6JA&_startIndex=10
2022-07-19 13:53:58,471 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): foobar.com:443
2022-07-19 13:54:01,043 DEBUG urllib3.connectionpool: https://foobar.com:443 "GET /ccm/oslc/projectareas?oslc_cm.pageSize=10&_resultToken=_eRmhQAdZEe2uavfh6co6JA&_startIndex=10 HTTP/1.1" 200 7559
2022-07-19 13:54:01,060 DEBUG client.RTCClient: Get response from https://foobar.com/ccm/oslc/projectareas?oslc_cm.pageSize=10&_resultToken=_eRmhQAdZEe2uavfh6co6JA&_startIndex=20
2022-07-19 13:54:01,063 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): foobar.com:443
2022-07-19 13:54:03,640 DEBUG urllib3.connectionpool: https://foobar.com:443 "GET /ccm/oslc/projectareas?oslc_cm.pageSize=10&_resultToken=_eRmhQAdZEe2uavfh6co6JA&_startIndex=20 HTTP/1.1" 500 239
2022-07-19 13:54:03,644 ERROR client.RTCClient: Failed GET request at <https://foobar.com/ccm/oslc/projectareas?oslc_cm.pageSize=10&_resultToken=_eRmhQAdZEe2uavfh6co6JA&_startIndex=20> with response: b'<?xml version="1.0" encoding="UTF-8"?><oslc_cm:error xmlns:oslc_cm="http://open-services.net/xmlns/cm/1.0/">\r\n<oslc_cm:status>500</oslc_cm:status>\r\n<oslc_cm:message>Query _eRmhQAdZEe2uavfh6co6JA expired.</oslc_cm:message>\r\n</oslc_cm:error>'
```
Immediatly opening the requested URL in the browser shows:
![grafik](https://user-images.githubusercontent.com/520251/179744858-a2ba1587-a0b2-464a-9dce-5a544956fa4e.png)

**Comment by TheAverageUser987** [comment]
Hi @dixudx, @Mershl 
I am also struggling a bit with Jazz 7.0.2. If I add the `auth=(self.username, self.password)` to the client.py I get no login errors but when I try to get an item I get the following. 

```
2022-07-28 16:40:27,068 ERROR client.RTCClient: not well-formed (invalid token): line 17, column 77
Traceback (most recent call last):
  File "C:\Users\######\AppData\Local\Programs\Python\Python36\lib\site-packages\rtcclient\client.py", line 958, in getWorkitem
    raw_data = xmltodict.parse(resp.content)
  File "C:\Users\######\AppData\Local\Programs\Python\Python36\lib\site-packages\xmltodict.py", line 378, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 17, column 77

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:/Users/######/Work/Test/rtcclienttest.py", line 20, in <module>
    wk = myclient.getWorkitem(856127) # get a workitem whose id is 123456
  File "C:\Users\######\AppData\Local\Programs\Python\Python36\lib\site-packages\rtcclient\client.py", line 972, in getWorkitem
    raise exception.NotFound("Not found <Workitem %s>" % workitem_id)
rtcclient.exception.NotFound: Not found <Workitem 856127>
```

**Comment by TheAverageUser987** [comment]
Update: the authentication seems to be not working, because using the wrong password will give the same result...

**Comment by dixudx** [comment]
> 2022-07-28 16:40:27,068 ERROR client.RTCClient: not well-formed (invalid token): line 17, column 77

> the authentication seems to be not working

Yeah, the authentication fails. 

Please try below solution from @Mershl. 

> All get requests in client.py without the explicit auth tuple report an 401 - Unauhorized error. This is fixed by adding an explicit auth=(self.username, self.password) to every self.get request coming from client.py.

**Comment by TheAverageUser987** [comment]
Yes I tried that, every get has now `auth=(self.username, self.password),` in the parameters. But I still have no access to the workitems

**Comment by dixudx** [comment]
@TheAverageUser987 Would you please share your rtcclient version, code snippet and detailed logs? Thanks

**Comment by gpongelli** [comment]
Hi,
I've done the same test with `getWorkitem` with released package 0.8.2 from pypi, I get the same two exception "ExpatError"  and "NotFound", even if the work item exists on jazz.

Trying to debug, the response received at [this line](https://github.com/dixudx/rtcclient/blob/0.8.2/rtcclient/client.py#L952) has status_code 200 but the content byte are an html webpage with something similar to an error :


```html
b'<!DOCTYPE html>\n<!--\n  Licensed Materials - Property of IBM\n  (c) Copyright IBM Corporation 2005, 2021. All Rights Reserved.\n  \n  Note to U.S. Government Users Restricted Rights:\n  Use, duplication or disclosure restricted by GSA ADP Schedule\n  Contract with IBM Corp.\n-->\n\n<html  lang="en-us">\n<head>\n<meta http-equiv="content-type" content="text/html; charset=UTF-8">\n<meta http-equiv="X-UA-Compatible" content="IE=10">\n<title></title>\n\n<link type="text/css" rel="stylesheet" href="/ccm/web/_style/?include=A~&etag=Hx5sxDxXiX5_en_US&_proxyURL=%2Fccm&ss=XGwKh">\n<link rel="shortcut icon" href="/ccm/web/net.jazz.ajax/jazz.ico">\n\n<style type="text/css">\n#net-jazz-ajax-NoScriptMessage {\n\twidth: 100%;\n\tcolor: #D0D0D0;\n\tfont-size: 2em;\n\ttext-align: center;\n\tposition: absolute;\n\ttop: 1%;\n\tz-index: 999;\n}\n</style>\n\n</head>\n\n<body class="claro">\n\t<noscript><div id="net-jazz-ajax-NoScriptMessage">Javascript is either disabled or not available in your Browser</div></noscript>\n\t<div id="net-jazz-ajax-InitialLoadMessage">Loading...</div>\n\t<div id="net-jazz-ajax-WorkbenchRoot"></div>\n\t\n\t<script type="text/javascript">\n\t\tdjConfig = {\n\t\t\tisDebug: false,\n\t\t\tlayout: "",\n\t\t\tusePlainJson: true,\n\t\t\tbaseUrl: "/ccm/web/dojo/",\n\t\t\tlocale: "en-us",\n\t\t\tlocalizationComplete: true\n\t\t};\n\t\t/*null*/\n\t\tnet = {jazz: {ajax: {}}};\n\t\tnet.jazz.ajax._contextRoot = "/ccm";\n\t\tnet.jazz.ajax._webuiPrefix = "/web/";\n\t</script>\n\t\n\t<script type="text/javascript" src="/ccm/web/_js/?include=A~&etag=Hx5sxDxXiX5_en_US&_proxyURL=%2Fccm&ss=XGwKh&locale=en-us"></script>\n\n<script type="text/javascript">\nrequire("dojo/main").getObject(\'jazz.core.loader\', true)._serverStartup="XGwKh";\nrequire("dojo/main").getObject(\'jazz.core.loader\',true)._loaded=["A"];\n</script>\n\n\t\n\t<script type="text/javascript">\n\t/* <![CDATA[ */\n\t\trequire(["dojo/ready", "dojo/parser", "dijit/registry", "dijit/Dialog"], function(ready, parser, registry){\n\t\t     ready(function(){\n\t\t        net.jazz.ajax.ui.PlatformUI.createAndRunWorkbench("net.jazz.web.app.authrequired");\n\t\t     });\n\t\t});\n\t/* ]]> */\n\t</script>\n</body>\n</html>\n'
```

**Comment by dixudx** [comment]
@gpongelli From the message,

> <link type="text/css" rel="stylesheet" href="/ccm/web/_style/?include=A~&etag=Hx5sxDxXiX5_en_US&_proxyURL=%2Fccm&ss=XGwKh">
> <noscript><div id="net-jazz-ajax-NoScriptMessage">Javascript is either disabled or not available in your Browser</div></noscript>
>
>  net.jazz.ajax.ui.PlatformUI.createAndRunWorkbench("net.jazz.web.app.authrequired");

@gpongelli It seems that `/ccm/web` was used as the url. Would you please use `https://xxx/ccm` instead and set `ends_with_jazz` to `False`. Give it a try.

The authentication and version skew of RTC are big headaches. We're trying to find a convergent way to handle the skews of authentications between different RTC configurations and versions.

**Comment by gpongelli** [comment]
> @gpongelli It seems that `/ccm/web` was used as the url. Would you please use `https://xxx/ccm` instead and set `ends_with_jazz` to `False`. Give it a try.
> 
> The authentication and version skew of RTC are big headaches. We're trying to find a convergent way to handle the skews of authentications between different RTC configurations and versions.


Here's the test from main's HEAD commit:

```python
    setup_basic_logging()

    url = "https://__the_url__/ccm"
    username = "my_user"
    password = "my_pass"
    myclient = RTCClient(url, username, password, ends_with_jazz=False)

    wk = myclient.getWorkitem(work_item_number)
```

result:

```
2023-03-24 11:41:52,185 DEBUG client.RTCClient: Get response from https://__the_url__/ccm/authenticated/identity
2023-03-24 11:41:52,192 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): __the_url__:443
2023-03-24 11:41:52,408 DEBUG urllib3.connectionpool: https://__the_url__:443 "GET /ccm/authenticated/identity HTTP/1.1" 302 0
2023-03-24 11:41:52,421 ERROR client.RTCClient: Failed GET request at <https://__the_url__/ccm/authenticated/identity> with response: b''
2023-03-24 11:41:52,421 DEBUG client.RTCClient: Get response from https://__the_url__/ccm/authenticated/identity
2023-03-24 11:41:52,423 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): __the_url__:443
2023-03-24 11:41:52,620 DEBUG urllib3.connectionpool: https://__the_url__:443 "GET /ccm/authenticated/identity HTTP/1.1" 302 0
2023-03-24 11:41:52,624 ERROR client.RTCClient: Failed GET request at <https://__the_url__/ccm/authenticated/identity> with response: b''
2023-03-24 11:41:53,017 DEBUG client.RTCClient: Get response from https://__the_url__/ccm/oslc/workitems/<work_item_number>
2023-03-24 11:41:53,020 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): __the_url__:443
2023-03-24 11:41:53,224 DEBUG urllib3.connectionpool: https://__the_url__:443 "GET /ccm/oslc/workitems/<work_item_number> HTTP/1.1" 302 0
2023-03-24 11:41:53,228 DEBUG urllib3.connectionpool: Resetting dropped connection: __the_url__
2023-03-24 11:41:53,412 DEBUG urllib3.connectionpool: https://__the_url__:443 "GET /ccm/secure/authenticated/identity?redirectPath=%2Fccm%2Foslc%2Fworkitems%2F<work_item_number> HTTP/1.1" 302 0
2023-03-24 11:41:53,419 DEBUG urllib3.connectionpool: Resetting dropped connection: __the_url__
2023-03-24 11:41:53,605 DEBUG urllib3.connectionpool: https://__the_url__:443 "GET /ccm/auth/authrequired HTTP/1.1" 200 1072
2023-03-24 11:42:18,409 INFO client.RTCClient: Cookie expires. Relogin to get a new cookie.
2023-03-24 11:42:18,410 DEBUG client.RTCClient: Get response from https://__the_url__/ccm/authenticated/identity
2023-03-24 11:42:18,413 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): __the_url__:443
2023-03-24 11:42:18,614 DEBUG urllib3.connectionpool: https://__the_url__:443 "GET /ccm/authenticated/identity HTTP/1.1" 302 0
2023-03-24 11:42:18,619 ERROR client.RTCClient: Failed GET request at <https://__the_url__/ccm/authenticated/identity> with response: b''
2023-03-24 11:42:18,619 DEBUG client.RTCClient: Get response from https://__the_url__/ccm/authenticated/identity
2023-03-24 11:42:18,621 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): __the_url__:443
2023-03-24 11:42:18,816 DEBUG urllib3.connectionpool: https://__the_url__:443 "GET /ccm/authenticated/identity HTTP/1.1" 302 0
2023-03-24 11:42:18,821 ERROR client.RTCClient: Failed GET request at <https://__the_url__/ccm/authenticated/identity> with response: b''
2023-03-24 11:42:18,821 DEBUG client.RTCClient: Successfully relogin.
2023-03-24 11:42:18,821 DEBUG client.RTCClient: Get response from https://__the_url__/ccm/oslc/workitems/<work_item_number>
2023-03-24 11:42:18,824 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): __the_url__:443
2023-03-24 11:42:19,027 DEBUG urllib3.connectionpool: https://__the_url__:443 "GET /ccm/oslc/workitems/<work_item_number> HTTP/1.1" 302 0
2023-03-24 11:42:19,032 DEBUG urllib3.connectionpool: Resetting dropped connection: __the_url__
2023-03-24 11:42:19,214 DEBUG urllib3.connectionpool: https://__the_url__:443 "GET /ccm/secure/authenticated/identity?redirectPath=%2Fccm%2Foslc%2Fworkitems%2F<work_item_number> HTTP/1.1" 302 0
2023-03-24 11:42:19,221 DEBUG urllib3.connectionpool: Resetting dropped connection: __the_url__
2023-03-24 11:42:19,413 DEBUG urllib3.connectionpool: https://__the_url__:443 "GET /ccm/auth/authrequired HTTP/1.1" 200 1072
2023-03-24 11:42:19,415 ERROR client.RTCClient: not well-formed (invalid token): line 17, column 77
Traceback (most recent call last):
  File "...\rtcclient\rtcclient\client.py", line 996, in getWorkitem
    raw_data = xmltodict.parse(resp.content)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\rtcclient\venv\Lib\site-packages\xmltodict.py", line 327, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 17, column 77

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\proj\002_GIT\PyCharmProjects\rtcclient\rtcclient\client.py", line 1010, in getWorkitem
    raise exception.NotFound("Not found <Workitem %s>" % workitem_id)
rtcclient.exception.NotFound: Not found <Workitem <work_item_number>>
python-BaseException
```

the content is the same as my [previous comment](https://github.com/dixudx/rtcclient/issues/166#issuecomment-1479851638) .



I found a way that works:
- tag 0.8.2
- code
```python
    url = "https://__the_url__:443/ccm/" 
    username = "my_user"
    password = "_my_pass"
    myclient = RTCClient(url, username, password, ends_with_jazz=False)

    wk = myclient.getWorkitem(work_item)
```

after this point I have a WorkItem object without exception.

**Comment by gpongelli** [comment]
> The authentication and version skew of RTC are big headaches. We're trying to find a convergent way to handle the skews of authentications between different RTC configurations and versions.

just to avoid too much headaches, is it possible to get server version information from API calls ? so the tool can behave differently depending on which server version is talking to.

**Comment by dixudx** [comment]
> is it possible to get server version information from API calls ? so the tool can behave differently depending on which server version is talking to.

Currently I did not find a way to get the meta information (including version, etc) without getting authenticated first.

Would you please help investigate this to find out some alternative ways. Thanks.

**Comment by dixudx** [comment]
> I found a way that works:
>
>    tag 0.6.0
>    that tag installs xmltodict==0.13.0 an
>    test code run:
>
>    url = "https://__the_url__:443/ccm/" 
>    username = "my_user"
>    password = "_my_pass"
>    myclient = RTCClient(url, username, password, ends_with_jazz=False)
>
>   wk = myclient.getWorkitem(work_item)
> after this point I have a WorkItem object without exception.

Glad to hear that v0.6.0 works for your env.

https://github.com/dixudx/rtcclient/pull/133 introduced incompatible authentication changes since v0.7.0, which works well with Jazz 6.0.6.1 and ELM Tool 7.0.
