### ISSUE TITLE
url not found: jazz/authenticated

### ISSUE THREAD

**Issue by gpongelli** [dixudx/rtcclient#174]
Hi,
I was trying to use your plugin to, at least, connect to a jazz server using your `get_workitem.py` script into `examples/how_to/workitem` folder.

I've changed the file with : 

```python
    url = "https://__the_url__:443/ccm/jazz"
    username = "my_username"
    password = "my_password"
    myclient = RTCClient(url, username, password, ends_with_jazz=True)
```

Adding also `ends_with_jazz=True` that I saw from docs/other issues.

This is the trace I get:

```python
2023-03-22 14:49:42,753 DEBUG client.RTCClient: Get response from https://__the_url__:443/ccm/jazz/authenticated/identity
2023-03-22 14:49:42,764 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): __the_url__:443
2023-03-22 14:49:42,979 DEBUG urllib3.connectionpool: https://__the_url__:443 "GET /ccm/jazz/authenticated/identity HTTP/1.1" 302 0
2023-03-22 14:49:43,000 DEBUG urllib3.connectionpool: Resetting dropped connection: __the_url__
2023-03-22 14:49:43,153 DEBUG urllib3.connectionpool: https://__the_url__:443 "GET /ccm/secure/authenticated/identity?redirectPath=%2Fccm%2Fjazz%2Fauthenticated%2Fidentity HTTP/1.1" 302 0
2023-03-22 14:49:43,167 DEBUG urllib3.connectionpool: Resetting dropped connection: __the_url__
2023-03-22 14:49:43,325 DEBUG urllib3.connectionpool: https://__the_url__:443 "GET /ccm/auth/authrequired HTTP/1.1" 200 1072
2023-03-22 14:49:48,130 DEBUG client.RTCClient: Get response from https://__the_url__:443/ccm/jazz/authenticated/identity
2023-03-22 14:49:48,141 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): __the_url__:443
2023-03-22 14:49:48,368 DEBUG urllib3.connectionpool: https://__the_url__:443 "GET /ccm/jazz/authenticated/identity HTTP/1.1" 302 0
2023-03-22 14:49:48,381 DEBUG urllib3.connectionpool: Resetting dropped connection: __the_url__
2023-03-22 14:49:48,543 DEBUG urllib3.connectionpool: https://__the_url__:443 "GET /ccm/secure/authenticated/identity?redirectPath=%2Fccm%2Fjazz%2Fauthenticated%2Fidentity HTTP/1.1" 302 0
2023-03-22 14:49:48,583 DEBUG urllib3.connectionpool: Resetting dropped connection: __the_url__
2023-03-22 14:49:48,837 DEBUG urllib3.connectionpool: https://__the_url__:443 "GET /ccm/auth/authrequired HTTP/1.1" 200 1072
2023-03-22 14:49:56,708 DEBUG client.RTCClient: Post a request to https://__the_url__:443/ccm/jazz/authenticated/j_security_check with data: {'j_username': 'my_username', 'j_password': 'my_password'} and json: None
2023-03-22 14:49:56,717 DEBUG urllib3.connectionpool: Starting new HTTPS connection (1): __the_url__:443
2023-03-22 14:49:57,598 DEBUG urllib3.connectionpool: https://__the_url__:443 "POST /ccm/jazz/authenticated/j_security_check HTTP/1.1" 302 0
2023-03-22 14:49:57,610 DEBUG urllib3.connectionpool: Resetting dropped connection: __the_url__
2023-03-22 14:49:57,768 DEBUG urllib3.connectionpool: https://__the_url__:443 "GET /ccm/jazz/authenticated/ HTTP/1.1" 404 None
2023-03-22 14:49:57,773 ERROR client.RTCClient: Failed POST request at <https://__the_url__:443/ccm/jazz/authenticated/j_security_check> with response: b'Error 404: Not Found\n'
2023-03-22 14:49:57,773 INFO client.RTCClient: 404
Traceback (most recent call last):

  File "...\rtcclient\examples\how_to\workitem\get_workitem.py", line 13, in <module>
    myclient = RTCClient(url, username, password, ends_with_jazz=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\rtcclient\rtcclient\client.py", line 77, in __init__
    self.headers = self._get_headers()
                   ^^^^^^^^^^^^^^^^^^^
  File "...\rtcclient\rtcclient\client.py", line 155, in _get_headers
    resp = self.post(self.url + "/authenticated/j_security_check",
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\rtcclient\rtcclient\utils.py", line 27, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "...\rtcclient\rtcclient\base.py", line 144, in post
    response.raise_for_status()
  File "...\rtcclient\venv\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://__the_url__/ccm/jazz/authenticated/
python-BaseException
```

So the point that raises exception is [this line](https://github.com/dixudx/rtcclient/blob/master/rtcclient/client.py#L136), the line number differs because of some tests I made related to cookies (from a fork), but those changes are commented.

Some information on my environment:

- Python3.11
- rtcclient checkout of main branch
- IBM Jazz 7.0.2

Thank you!

**Comment by dixudx** [comment]
https://github.com/dixudx/rtcclient/pull/133 introduced incompatible authentication changes since v0.7.0, which works well with Jazz 6.0.6.1 and ELM Tool 7.0.

@gpongelli What is your RTC server version? Maybe the rtcclient version is not compatible with older RTC server. Here is [a version skew note of rtcclient](https://github.com/dixudx/rtcclient#python--rational-team-concert-versions).

Would you please try older rtcclient version `v0.6.0` (`pip install -U rtcclient==0.6.0`) to see whether it works in your environment.

**Comment by dixudx** [comment]
> just for completeness, if I use the 0.8.2 version from pypi in a different project and run the same script, it fail in a https://github.com/dixudx/rtcclient/issues/166#issuecomment-1198251273

The distinguished difference between `main` branch and release `0.8.2` is [this commit](https://github.com/dixudx/rtcclient/commit/b35deed7660a5d52eaaa245ea87a9883bc353d08).

**Comment by gpongelli** [comment]
> @gpongelli What is your RTC server version? Maybe the rtcclient version is not compatible with older RTC server. Here is [a version skew note of rtcclient](https://github.com/dixudx/rtcclient#python--rational-team-concert-versions).

IBM server is 7.0.2 (it’s the information I use when I open case to IBM).
I’ll try to deeply check about RTC version.


> Would you please try older rtcclient version `v0.6.0` (`pip install -U rtcclient==0.6.0`) to see whether it works in your environment.

I can try and let you know, but probably I’m on more recent server version.

**Comment by dixudx** [comment]
> probably I’m on more recent server version.

Sure. Thanks.

**Comment by gpongelli** [comment]
> #133 introduced incompatible authentication changes since v0.7.0, which works well with Jazz 6.0.6.1 and ELM Tool 7.0.
> 
> @gpongelli What is your RTC server version? Maybe the rtcclient version is not compatible with older RTC server. Here is [a version skew note of rtcclient](https://github.com/dixudx/rtcclient#python--rational-team-concert-versions).
> 
> Would you please try older rtcclient version `v0.6.0` (`pip install -U rtcclient==0.6.0`) to see whether it works in your environment.

just tried with version 0.6.0 with `myclient = RTCClient(url, username, password, ends_with_jazz=True)` ,  this is the exception I get

```
2023-03-24 11:29:47,810 ERROR client.RTCClient: Failed POST request at <https://__the_url__:443/ccm/jazz/authenticated/j_security_check> with response: b'Error 404: Not Found\n'
2023-03-24 11:29:47,811 INFO client.RTCClient: 404
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3.2\plugins\python-ce\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2022.3.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\proj\002_GIT\PyCharmProjects\jazz_client\main.py", line 11, in <module>
    myclient = RTCClient(url, username, password, ends_with_jazz=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gpongelli\AppData\Local\pypoetry\Cache\virtualenvs\jazz-client--c_pCylz-py3.11\Lib\site-packages\rtcclient\client.py", line 65, in __init__
    self.headers = self._get_headers()
                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gpongelli\AppData\Local\pypoetry\Cache\virtualenvs\jazz-client--c_pCylz-py3.11\Lib\site-packages\rtcclient\client.py", line 99, in _get_headers
    resp = self.post(self.url + "/authenticated/j_security_check",
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gpongelli\AppData\Local\pypoetry\Cache\virtualenvs\jazz-client--c_pCylz-py3.11\Lib\site-packages\rtcclient\utils.py", line 22, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gpongelli\AppData\Local\pypoetry\Cache\virtualenvs\jazz-client--c_pCylz-py3.11\Lib\site-packages\rtcclient\base.py", line 123, in post
    response.raise_for_status()
  File "C:\Users\gpongelli\AppData\Local\pypoetry\Cache\virtualenvs\jazz-client--c_pCylz-py3.11\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://__the_url__/ccm/jazz/authenticated/
```

**Comment by dixudx** [comment]
From https://github.com/dixudx/rtcclient/issues/166#issuecomment-1482610851, it seems `myclient = RTCClient(url, username, password, ends_with_jazz=False)` works with rtcclient 0.6.0.
