### ISSUE TITLE
Authentication requires no forwarding and different cookie handling (on my RTC installation)

### ISSUE THREAD

**Issue by nsc-deb** [dixudx/rtcclient#68]
When testing the _rtcclient_ library against an RTC 5.0.2 installation I have access to I noticed that I needed to disable automatic forward handling and to keep track on more cookies in order to be able to authenticate correctly.

Following the previous private mails I disabled http requests in `_get_headers` (even though only the first two seem to be neccessary) and still get errors:

      File "/home/nsc/rtcclient/rtcclient/client.py", line 118, in getProjectAreas
        returned_properties=returned_properties)
      File "/home/nsc/rtcclient/rtcclient/client.py", line 172, in _getProjectAreas
        filter_rule=filter_rule)
      File "/home/nsc/rtcclient/rtcclient/client.py", line 1309, in _get_paged_resources
        raw_data = xmltodict.parse(resp.content)
      File "/usr/lib/python2.7/dist-packages/xmltodict.py", line 248, in parse
        parser.Parse(xml_input, True)
    xml.parsers.expat.ExpatError: not well-formed (invalid token): line 21, column 77

The cookies I retrieve look like this:

    line 68: set-cookie: WASReqURL=https:///ccm/authenticated/identity; Path=/; HttpOnly
    line 77: set-cookie: LtpaToken2=G1oEy1FJVPYObrxLCOROVAVmY4OJPBUsUb0xY7rH8AS/omqr56uvsU1wz9A4Y6p22W9Hf+h9BV31SitGyzLS/S+cRiQ9IWcFMosUVuean/y5JRAQl2mIvJnL1Ygw/s3/ZEsmN1h+H78hjGJ4cJKhgqhggEwGuSm7idgX2NIo4r3wgxNKkRg/0cPCBk9hsA5vVsA96hQbe5td5R/ksVE4gDrGpfjmGNiRxnGrMSXzLvBP9J6cLZowLAkWBmlPrmo+/MYA0C6R9x7uGdh1GtKQCt14m14QRXwFs32HFqRlKejU6aZCJdz/ARWH+3P5TTy3Lnx+yNv7jNgLGg7tjkZn2jCzBcQtTdNjUaO8pSN/Nb8C7aH/XzVNheDezCTUKmQLADlpzoWkqS5QTViySGqXKZjDKEf9sbTVYoADS5Yp6j6idNg3hBAvB/ynk3Ov3ohdTPWICwn7Apo50dSKd6bbgyvvQtKDZqDuJZU+PzBbJ52g0KOApyJi0yhtlaQBecuz8CU0PQw4wzAplNDC487eTW1Jbcstcn+KokepFQEan/Rj7WzZajsGdPWmU46PkjdQEC7TLuSPBCv71dRBa44hhELKb4z3lUHarLKEYuxSRWuyfdHP1ojG4Dsu9ZQVB7HXJAX5AJqIML8IGQq/AFvdg9wXf1VxyoPQv8jeexncLE4rnMGKCJR1xvGlHW7G0gEz; Path=/; HttpOnly
    line 88: set-cookie: JSESSIONID=0000WqEIzzeJ7aVlKGZUij_wBsn:-1; Path=/; HttpOnly, X-com-ibm-team-foundation-auth-loop-avoidance=false; Secure

To be able to authenticate successfully I need (only) the cookie received after the POST request (`/authenticated/j_security_check`, line 77); the other cookies do not disturb.

Thanks for your efforts and kind regards
Nicolas

**Comment by dixudx** [comment]
@nsc-deb Is your  RTC server deployed in a reverse proxy server?

The set-cookie in your first GET method in line 69 and line77 seems quite weird

**Comment by dixudx** [comment]
@nsc-deb I will test again when disabling allow_redirects and found it out whether it behaved the same in my RTC environment.

**Comment by dixudx** [comment]
@nsc-deb I've tested *allow_redirects=False* against my rtcclient, where it works the same as *allow_redirects=True*, including the data format of *set-cookie* (the actual data is slightly different)

> JSESSIONID=ADE77264BBD8F724DA3D0AF7CA82942A; Path=/; Secure; HttpOnly, JazzFormAuth=Form; Path=/jazz; Secure, x-com-ibm-team-scenario=ba2d3a44-a4bb-4467-9090-92a41efcb3b5%3Bname%3DInitial+Page+Load%3Bextras%3D%2Fjazz%2Fauthenticated%2Fidentity%2C1448273683257; Path=/

Can you provide the client log (enable debug log mode) in detail ?

**Comment by nsc-deb** [comment]
In general there is proxy server setup in our network, but I have no 
clue how the RTC server is deployed (I do have only user level access).

**Comment by nsc-deb** [comment]
As requested: tested with *allow_redirects=False*, with and without 
modified cookie handling.

2015-11-23 12:51:48,136 DEBUG client.RTCClient: Get response from https://rtc.local/ccm/authenticated/identity
2015-11-23 12:51:48,138 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): rtc.local
/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
2015-11-23 12:51:48,149 DEBUG requests.packages.urllib3.connectionpool: "GET /ccm/authenticated/identity HTTP/1.1" 302 0
2015-11-23 12:51:48,150 ERROR client.RTCClient: Failed GET request at <https://rtc.local/ccm/authenticated/identity> with response: 
2015-11-23 12:51:48,150 DEBUG client.RTCClient: Post a request to https://rtc.local/ccm/authenticated/j_security_check with data: j_username=XXX&j_password=XXX and json: None
2015-11-23 12:51:48,151 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): rtc.local
2015-11-23 12:51:48,162 DEBUG requests.packages.urllib3.connectionpool: "POST /ccm/authenticated/j_security_check HTTP/1.1" 302 0
2015-11-23 12:51:48,163 ERROR client.RTCClient: Failed POST request at <https://rtc.local/ccm/authenticated/j_security_check> with response: 
2015-11-23 12:51:48,163 INFO client.RTCClient: 302
2015-11-23 12:51:48,163 DEBUG client.RTCClient: Get response from https://rtc.local/ccm/authenticated/identity
2015-11-23 12:51:48,164 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): rtc.local
2015-11-23 12:51:48,175 DEBUG requests.packages.urllib3.connectionpool: "GET /ccm/authenticated/identity HTTP/1.1" 302 0
2015-11-23 12:51:48,176 ERROR client.RTCClient: Failed GET request at <https://rtc.local/ccm/authenticated/identity> with response: 
Getting list of all workitems2015-11-23 12:51:48,176 DEBUG client.RTCClient: Start to fetch all ProjectAreas with [ProjectArea ID: not specified] and [archived=False]
2015-11-23 12:51:48,176 DEBUG client.RTCClient: Get response from https://rtc.local/ccm/oslc/projectareas?oslc_cm.pageSize=10&_startIndex=0
2015-11-23 12:51:48,177 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): rtc.local
2015-11-23 12:51:48,187 DEBUG requests.packages.urllib3.connectionpool: "GET /ccm/oslc/projectareas?oslc_cm.pageSize=10&_startIndex=0 HTTP/1.1" 302 0
2015-11-23 12:51:48,189 DEBUG requests.packages.urllib3.connectionpool: "GET /ccm/authenticated/identity?redirectPath=%2Fccm%2Foslc%2Fprojectareas%3Foslc_cm.pageSize%3D10%26_startIndex%3D0 HTTP/1.1" 302 0
2015-11-23 12:51:48,191 DEBUG requests.packages.urllib3.connectionpool: "GET /ccm/auth/authrequired HTTP/1.1" 200 None
Traceback (most recent call last):
  File "get_workitem.py", line 36, in <module>
    returned_properties="dc:identifier")
  File "/home/nsc/rtcclient/rtcclient/client.py", line 915, in getWorkitems
    pa_ids = self.getProjectAreaIDs(projectarea_name)
  File "/home/nsc/rtcclient/rtcclient/client.py", line 251, in getProjectAreaIDs
    projectareas = self.getProjectAreas(archived=archived)
  File "/home/nsc/rtcclient/rtcclient/client.py", line 115, in getProjectAreas
    returned_properties=returned_properties)
  File "/home/nsc/rtcclient/rtcclient/client.py", line 169, in _getProjectAreas
    filter_rule=filter_rule)
  File "/home/nsc/rtcclient/rtcclient/client.py", line 1306, in _get_paged_resources
    raw_data = xmltodict.parse(resp.content)
  File "/usr/lib/python2.7/dist-packages/xmltodict.py", line 248, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 21, column 77

2015-11-23 12:51:24,240 DEBUG client.RTCClient: Get response from https://rtc.local/ccm/authenticated/identity
2015-11-23 12:51:24,243 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): rtc.local
/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
2015-11-23 12:51:24,253 DEBUG requests.packages.urllib3.connectionpool: "GET /ccm/authenticated/identity HTTP/1.1" 302 0
2015-11-23 12:51:24,253 ERROR client.RTCClient: Failed GET request at <https://rtc.local/ccm/authenticated/identity> with response: 
2015-11-23 12:51:24,253 DEBUG client.RTCClient: Post a request to https://rtc.local/ccm/authenticated/j_security_check with data: j_username=XXX&j_password=XXX and json: None
2015-11-23 12:51:24,254 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): rtc.local
2015-11-23 12:51:24,264 DEBUG requests.packages.urllib3.connectionpool: "POST /ccm/authenticated/j_security_check HTTP/1.1" 302 0
2015-11-23 12:51:24,265 ERROR client.RTCClient: Failed POST request at <https://rtc.local/ccm/authenticated/j_security_check> with response: 
2015-11-23 12:51:24,265 INFO client.RTCClient: 302
2015-11-23 12:51:24,265 DEBUG client.RTCClient: Get response from https://rtc.local/ccm/authenticated/identity
2015-11-23 12:51:24,266 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): rtc.local
2015-11-23 12:51:24,276 DEBUG requests.packages.urllib3.connectionpool: "GET /ccm/authenticated/identity HTTP/1.1" 200 None
Getting list of all workitems2015-11-23 12:51:24,277 DEBUG client.RTCClient: Start to fetch all ProjectAreas with [ProjectArea ID: not specified] and [archived=False]
2015-11-23 12:51:24,277 DEBUG client.RTCClient: Get response from https://rtc.local/ccm/oslc/projectareas?oslc_cm.pageSize=10&_startIndex=0
2015-11-23 12:51:24,278 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): rtc.local
2015-11-23 12:51:24,299 DEBUG requests.packages.urllib3.connectionpool: "GET /ccm/oslc/projectareas?oslc_cm.pageSize=10&_startIndex=0 HTTP/1.1" 200 1550
2015-11-23 12:51:24,300 DEBUG project_area.ProjectArea: Get response from https://rtc.local/ccm/oslc/projectareas/_IN8PQAZwEeO_X495CZNymg/rtc_cm:members
2015-11-23 12:51:24,301 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): rtc.local
...

**Comment by nsc-deb** [comment]
Sorry for the last comment; I hoped that mail2github handles text attachments more beautiful...

[authentication-failure--disabled-forwarding--default-cookie-handling.txt](https://github.com/dixudx/rtcclient/files/41534/authentication-failure--disabled-forwarding--default-cookie-handling.txt)
[authentication-failure--disabled-forwarding--modified-cookie-handling.txt](https://github.com/dixudx/rtcclient/files/41537/authentication-failure--disabled-forwarding--modified-cookie-handling.txt)

**Comment by dixudx** [comment]
@nsc-deb your RTC Server's url is https://rtc.local/ccm ? The default port of RTC Server is 9443. I guess your reverse proxy server redirects to port 80. So the your correct RTC servers's url is https://rtc.local.

**Comment by dixudx** [comment]
You can use markdown to quote your logs and codes.

**Comment by nsc-deb** [comment]
The Jazz login scheme is visible at [https://rtc.local/ccm](), at [https://rtc.local/]() are also some other IBM things installed and if I use this URL I get:

    Traceback (most recent call last):
      File "get_workitem.py", line 28, in <module>
        myclient = RTCClient(url, username, password)
      File "/home/nsc/rtcclient/rtcclient/client.py", line 52, in __init__
        self.headers = self._get_headers()
      File "/home/nsc/rtcclient/rtcclient/client.py", line 71, in _get_headers
        allow_redirects=False)
      File "/home/nsc/rtcclient/rtcclient/base.py", line 76, in get
        response.raise_for_status()
      File "/usr/lib/python2.7/dist-packages/requests/models.py", line 837, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url:  https://rtc.local/authenticated/identity

**Comment by dixudx** [comment]
From your logs

```
2015-11-23 12:51:48,136 DEBUG client.RTCClient: Get response from https://rtc.local/ccm/authenticated/identity
2015-11-23 12:51:48,138 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): rtc.local
/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
2015-11-23 12:51:48,149 DEBUG requests.packages.urllib3.connectionpool: "GET /ccm/authenticated/identity HTTP/1.1" 302 0
2015-11-23 12:51:48,150 ERROR client.RTCClient: Failed GET request at <https://rtc.local/ccm/authenticated/identity> with response:
```

and 

```
2015-11-23 12:51:24,240 DEBUG client.RTCClient: Get response from https://rtc.local/ccm/authenticated/identity
2015-11-23 12:51:24,243 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): rtc.local
/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
2015-11-23 12:51:24,253 DEBUG requests.packages.urllib3.connectionpool: "GET /ccm/authenticated/identity HTTP/1.1" 302 0
2015-11-23 12:51:24,253 ERROR client.RTCClient: Failed GET request at <https://rtc.local/ccm/authenticated/identity> with response:
```

Both the first GET requests failed.

The status code 302 means the requested resource resides temporarily under a different URI.

**Comment by dixudx** [comment]
You are right!  The correct Jazz login scheme is at <https://rtc.local/ccm> in your RTC environment. 

I seem to get a clue.

@nsc-deb try to visit <https://rtc.local/jazz/authenticated/identity>, see what you get. Suggest you open this link in a private window/tab (aka Going incognito in Chrome) to avoid using your previous web cookies. Can you see the Jazz login scheme ?

**Comment by nsc-deb** [comment]
At [https://rtc.local/jazz/authenticated/identity]() I get:

	Not Found
	
	The requested URL /jazz/authenticated/identity was not found on this server.
	IBM_HTTP_Server at rtc.local Port 443

whereas [https://rtc.local/ccm/authenticated/identity]() redirects my browser
to [https://rtc.local/ccm/auth/authrequired]() and the login scheme.

**Comment by dixudx** [comment]
> Not Found

> The requested URL /jazz/authenticated/identity was not found on this server.
> IBM_HTTP_Server at rtc.local Port 443

Port 443? What does this port do? Try to access <https://rtc.local:443/jazz/authenticated/identity> and <https://rtc.local:9443/jazz/authenticated/identity>

Moreover, with your added cookie, the requests afterwards do return 200. But it still quite annoy me how it works for using the previous bad GET and POST requests' `set-cookie`.

**Comment by dixudx** [comment]
And your solution do no harm to my client. It still works for my Jazz environment.

One more thing, when you set `allow_redirects=True` or leave it to default value `True` and enable your added cookie, can you still get the resources as well ?

**Comment by nsc-deb** [comment]
Port 443 is the default HTTPS port, thus when I access [https://rtc.local:443/jazz/authenticated/identity]() I get the same error as mentioned above.  Visiting [https://rtc.local:9443/jazz/authenticated/identity]() results in:

    Error 404: com.ibm.ws.webcontainer.servlet.exception.NoTargetForURIException: No target servlet configured for uri: /jazz/authenticated/identity 

While [https://rtc.local:9443/ccm/authenticated/identity]() forwards me to [https://rtc.local:9443/ccm/auth/authrequired]() and presents me the login scheme.


With `allow_redirects=True` it does not matter, whether I keep more cookie data or not, it always results in such debug output:

    2015-11-23 14:21:06,543 DEBUG client.RTCClient: Get response from https://rtc.local/ccm/authenticated/identity
    2015-11-23 14:21:06,545 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): rtc.local
    /usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html InsecureRequestWarning)
    2015-11-23 14:21:06,555 DEBUG requests.packages.urllib3.connectionpool: "GET /ccm/authenticated/identity HTTP/1.1" 302 0
    2015-11-23 14:21:06,558 DEBUG requests.packages.urllib3.connectionpool: "GET /ccm/auth/authrequired HTTP/1.1" 200 None
    2015-11-23 14:21:06,559 DEBUG client.RTCClient: Post a request to https://rtc.local/ccm/authenticated/j_security_check with data: j_username=XXX&j_password=XXX and json: None
    2015-11-23 14:21:06,559 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): rtc.local
    2015-11-23 14:21:06,569 DEBUG requests.packages.urllib3.connectionpool: "POST /ccm/authenticated/j_security_check HTTP/1.1" 302 0
    2015-11-23 14:21:06,572 DEBUG requests.packages.urllib3.connectionpool: "GET /ccm/authenticated/ HTTP/1.1" 404 None
    2015-11-23 14:21:06,573 ERROR client.RTCClient: Failed POST request at <https://rtc.local/ccm/authenticated/j_security_check> with response: Error 404: 

    2015-11-23 14:21:06,573 INFO client.RTCClient: 404
    Traceback (most recent call last):
      File "get_workitem.py", line 28, in <module>
        myclient = RTCClient(url, username, password)
      File "/home/nsc/rtcclient/rtcclient/client.py", line 52, in __init__
        self.headers = self._get_headers()
      File "/home/nsc/rtcclient/rtcclient/client.py", line 82, in _get_headers
        allow_redirects=True)
      File "/home/nsc/rtcclient/rtcclient/base.py", line 109, in post
        response.raise_for_status()
      File "/usr/lib/python2.7/dist-packages/requests/models.py", line 837, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://rtc.local/ccm/authenticated/

**Comment by dixudx** [comment]
So here I suggest you use <https://rtc.local:9443/ccm> instead of <https://rtc.local/ccm> as the rtc server url without any other code modifications (including `set-cookie`). And see what happened. This rtcclient should works well this time.

**Comment by nsc-deb** [comment]
OK.  I checked-out original 0.4.0 and use [https://rtc.local:9443/ccm]() and get:

    2015-11-23 14:36:30,647 DEBUG client.RTCClient: Get response from https://rtc.local:9443/ccm/authenticated/identity
    2015-11-23 14:36:30,649 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): rtc.local
    /usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
      InsecureRequestWarning)
    2015-11-23 14:36:30,665 DEBUG requests.packages.urllib3.connectionpool: "GET /ccm/authenticated/identity HTTP/1.1" 302 0
    2015-11-23 14:36:30,667 DEBUG requests.packages.urllib3.connectionpool: "GET /ccm/auth/authrequired HTTP/1.1" 200 None
    2015-11-23 14:36:30,668 DEBUG client.RTCClient: Post a request to https://rtc.local:9443/ccm/authenticated/j_security_check with data: j_username=XXX&j_password=XXX and json: None
    2015-11-23 14:36:30,669 INFO requests.packages.urllib3.connectionpool: Starting new HTTPS connection (1): rtc.local
    2015-11-23 14:36:30,683 DEBUG requests.packages.urllib3.connectionpool: "POST /ccm/authenticated/j_security_check HTTP/1.1" 302 0
    2015-11-23 14:36:30,687 DEBUG requests.packages.urllib3.connectionpool: "GET /ccm/authenticated/ HTTP/1.1" 404 None
    2015-11-23 14:36:30,687 ERROR client.RTCClient: Failed POST request at <https://rtc.local:9443/ccm/authenticated/j_security_check> with response: Error 404: 
    
    2015-11-23 14:36:30,688 INFO client.RTCClient: 404
    Traceback (most recent call last):
      File "./workitem.py", line 29, in <module>
        myclient = RTCClient(url, username, password)
      File "/home/nsc/rtcclient/rtcclient/client.py", line 52, in __init__
        self.headers = self._get_headers()
      File "/home/nsc/rtcclient/rtcclient/client.py", line 80, in _get_headers
        headers=_headers)
      File "/home/nsc/rtcclient/rtcclient/base.py", line 109, in post
        response.raise_for_status()
      File "/usr/lib/python2.7/dist-packages/requests/models.py", line 837, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://rtc.local:9443/ccm/authenticated/

Slowly I get the feeling that our local RTC installation is probably a bit weird...

**Comment by dixudx** [comment]
Now this time, the first GET request returned `200` instead of `302`. Still **bad POST** request.

hmm....Anyway, you have already found out a way to solve this problem against your Jazz environment.

So would you please update your patches here and it would be better to diff them. And others can apply your patches to the rtcclient if they have met the same Jazz RTC server problems as yours.

Thanks so much.

**Comment by nsc-deb** [comment]
Here are my two and a half patches, based on tag 0.4.0:

1. Disabling HTTP redirects during authorisation  
    [0001-disable-HTTP-redirects-during-authorisation.patch.txt](https://github.com/dixudx/rtcclient/files/42460/0001-disable-HTTP-redirects-during-authorisation.patch.txt)

2. Modified cookie handling  
    * For my site, this version (0002a) is sufficient:  
      [0002a-remember-other-cookies-set-during-authorisation.patch.txt](https://github.com/dixudx/rtcclient/files/42462/0002a-remember-other-cookies-set-during-authorisation.patch.txt)

    * but probably other sites need to use the last received cookie, thus (0002b):  
      [0002b-remember-more-cookies-set-during-authorisation.patch.txt](https://github.com/dixudx/rtcclient/files/42463/0002b-remember-more-cookies-set-during-authorisation.patch.txt)

Thanks for all your patients and efforts!

**Comment by dixudx** [comment]
@nsc-deb Thanks for your contribution.

For patchset 1, I will add an optional parameter `allow_redirects` to specify whether or not to redirect the url in the next release. One more question here, do you have to disable all the request redirects on other methods of this rtcclient ? such as `RTCClient.getProjectArea`, `RTCClient.getWorkitem` and etc.

For patchset 2, it does no harm to the current rtcclient and works well against my Jazz environment. I think we can incorporate this to the rtcclient. But more tests have to be conducted first. @nsc-deb You can also fully tests this patchset against your Jazz environment and commit this to rtcclient after that.

I really appreciate what you have done.

**Comment by nsc-deb** [comment]
I need to disable redirects only during authentication.  Especially `getProjectArea` and `getWorkitem` work w/o any further changes (and more I haven't tested yet).

**Comment by dixudx** [comment]
* fix this issue and build the patchsets into new lease 0.5.0
* you can install & update this client using `pip`: `pip install -U rtcclient`
